// Auto-discovered campaign chapter; keep this module data-only and deterministic.
export default {
  id: 'level-4',
  index: 4,
  name: 'Server Farm',
  exit: { label: 'SHAFT' },
  copy: {
    classification: 'THRESHOLD ARCHIVE / LEVEL 4',
    status: 'RACK POWER DEGRADED',
    start: {
      kicker: 'COLD AISLE / NO TECHNICIANS',
      title: 'THE RACKS<br />ARE LISTENING.',
      body: 'Seat three power cells. Ignore fans that spin toward you when the aisle is empty.',
      button: 'ENTER LEVEL 4',
    },
    pause: {
      kicker: 'PACKET LOSS 100%',
      title: 'THE HUM<br />KNOWS YOUR NAME.',
      body: 'Status LEDs keep blinking in a pattern that matches your pulse.',
      button: 'RECONNECT',
    },
    death: {
      kicker: 'PROCESS KILLED',
      title: 'ACCESS<br />REVOKED.',
      body: 'The crash dump lists one unauthorized heat signature.',
      button: 'COLD BOOT',
    },
    win: {
      kicker: 'EMERGENCY SHAFT OPEN',
      title: 'THE FANS<br />POINT DOWN.',
      body: 'A service shaft drops into refrigerated dark. Condensation beads on the ladder.',
      button: 'DESCEND TO LEVEL 5',
    },
  },
  maze: {
    desktop: { cols: 21, rows: 21 },
    mobile: { cols: 17, rows: 17 },
    loopRatio: 0.2,
    roomDivisor: 48,
    minimumRooms: 8,
    roomSize: { min: 2, max: 3 },
    seedSalt: 0x165667b1,
  },
  surfaces: {
    wall: {
      base: [58, 72, 78],
      accent: [40, 54, 60],
      grime: [22, 30, 34],
      pattern: 'painted-concrete',
      roughness: 0.82,
      metalness: 0.08,
      bumpScale: 0.055,
      grimeOpacity: 0.16,
    },
    floor: {
      base: [48, 54, 58],
      accent: [34, 40, 44],
      grime: [24, 28, 30],
      pattern: 'oil-stained-concrete',
      roughness: 0.74,
      metalness: 0.12,
      bumpScale: 0.04,
    },
    ceiling: {
      base: [52, 62, 68],
      accent: [36, 46, 52],
      grime: [20, 28, 32],
      pattern: 'service-slab',
      roughness: 0.8,
      metalness: 0.14,
      bumpScale: 0.044,
      emissive: 0x0e1a22,
      emissiveIntensity: 0.22,
    },
    trim: { color: 0x2e3c44, roughness: 0.7, metalness: 0.28 },
  },
  fog: {
    color: 0x1a2830,
    density: { desktop: 0.038, mobile: 0.046 },
  },
  lighting: {
    exposure: 0.7,
    hemisphere: {
      sky: 0x7aa8b8,
      ground: 0x0e161a,
      intensity: { desktop: 0.4, mobile: 0.48 },
    },
    ambient: {
      color: 0x3a5864,
      intensity: { desktop: 0.16, mobile: 0.22 },
    },
    fixture: {
      color: 0xb8e4f0,
      panelColor: 0xc8eef8,
      deadPanelColor: 0x2a3840,
      intensity: 88,
      distance: 10.4,
      angle: 1.16,
      penumbra: 0.84,
      decay: 2,
      brokenChance: 0.2,
      pool: { desktop: 6, mobile: 3 },
      flicker: {
        idleRate: 6.4,
        idleDepth: 0.04,
        faultFloor: 0.015,
        recovery: 0.32,
      },
    },
  },
  audio: {
    drips: false,
    masterGain: 0.75,
    humGain: 0.078,
    oscillators: [
      { frequency: 48, type: 'sine', gain: 0.22 },
      { frequency: 96, type: 'sawtooth', gain: 0.032 },
      { frequency: 192, type: 'triangle', gain: 0.02 },
      { frequency: 24, type: 'sine', gain: 0.14 },
    ],
    noise: { filter: 'bandpass', frequency: 720, q: 0.85, gain: 0.04 },
    heartbeat: { startFrequency: 60, endFrequency: 33 },
    impact: { startFrequency: 44, endFrequency: 15 },
    footstep: { walkLowpass: 360, runLowpass: 470 },
    ambience: {
      interval: [11, 24],
      cues: ['relay-chatter', 'machine-dropout', 'steam-release', 'fluorescent-dropout'],
      stereoWidth: 0.9,
      silenceChance: 0.24,
    },
  },
  objective: {
    type: 'fuse',
    count: 3,
    color: 0x5ec8e0,
    labels: {
      hud: 'THE RACKS ARE DYING',
      item: 'CELL',
      itemPlural: 'CELLS',
      interact: 'E  SEAT CELL',
      progress: 'CELLS {current}/{total}',
      locked: 'THE SHAFT WILL NOT OPEN',
      complete: 'POWER HOLDS / FIND THE SHAFT',
    },
  },
  props: [
    { type: 'cable-tray', density: 0.09, color: 0x2a3840, accent: 0x12181c, cluster: [2, 5] },
    { type: 'cable-tray', density: 0.03, color: 0x3a4850, accent: 0x1a2228, cluster: [1, 2] },
    { type: 'service-crate', density: 0.028, color: 0x4a5860, accent: 0x243038, cluster: [1, 3] },
    { type: 'square-column', density: 0.042, color: 0x3a4850, accent: 0x1e2a30, cluster: [1, 2] },
    { type: 'ceiling-vent', density: 0.04, color: 0x36444c, accent: 0x141c20, cluster: [1, 3] },
  ],
  incidents: {
    density: 0.015,
    minCount: 2,
    maxCount: 7,
    minCellDistance: 3,
    weights: {
      'collapsed-wanderer': 0.55,
      'abandoned-pack': 1.8,
      'chair-pile': 0.4,
      'black-motes': 1.6,
      'shoe-trail': 1.1,
    },
    palette: { cloth: 0x1e2a30, clothLight: 0x3a4c54, motes: 0x04080c },
  },
  atmosphere: {
    identity: 'haunted-cold-aisle',
    cadence: { first: [12, 22], interval: [16, 30] },
    pauseDuringChase: true,
    environmentalStory: [
      { id: 'uptime', text: 'UPTIME: 9999d / LAST HUMAN: UNKNOWN', density: 0.008, placement: 'wall' },
      { id: 'hot-aisle', text: 'HOT AISLE TEMPERATURE: BODY HEAT', density: 0.007, placement: 'wall' },
      { id: 'ticket', text: 'TICKET #0 / ASSIGNED TO YOU YESTERDAY', density: 0.005, placement: 'objective' },
    ],
    milestones: [
      {
        id: 'fan-spin',
        progress: 0.33,
        message: 'A DEAD FAN STARTS SPINNING TOWARD YOU',
        duration: 1.2,
        cue: 'relay-chatter',
        effect: { flicker: 0.5 },
      },
      {
        id: 'packet-echo',
        progress: 0.66,
        message: 'YOUR FOOTSTEPS ECHO AS PACKET LOSS',
        duration: 1.25,
        cue: 'machine-dropout',
        effect: { glitch: 0.4 },
      },
    ],
    events: [
      {
        id: 'led-chase',
        earliest: 8,
        weight: 1.2,
        maxRepeats: 3,
        tension: [0.05, 0.84],
        message: 'STATUS LIGHTS CHASE YOU DOWN THE AISLE',
        duration: 1.05,
        cue: 'relay-chatter',
        effect: { flicker: 0.6 },
      },
      {
        id: 'fan-breath',
        earliest: 17,
        weight: 0.95,
        maxRepeats: 2,
        tension: [0.12, 0.86],
        message: 'THE COOLING FANS INHALE AS ONE',
        duration: 1.12,
        cue: 'steam-release',
        pan: 'random',
      },
      {
        id: 'disk-spin',
        earliest: 25,
        weight: 0.7,
        maxRepeats: 2,
        tension: [0.18, 0.8],
        message: 'A DRIVE SPINS UP WITH NO POWER',
        duration: 1.15,
        cue: 'machine-dropout',
        effect: { silence: 0.6 },
      },
      {
        id: 'badge-beep',
        earliest: 33,
        weight: 0.58,
        maxRepeats: 1,
        tension: [0.2, 0.74],
        message: 'A BADGE READER ACCEPTS AN EMPTY HAND',
        duration: 1.1,
        cue: 'shift-bell',
      },
      {
        id: 'aisle-dark',
        earliest: 42,
        weight: 0.5,
        maxRepeats: 1,
        tension: [0.3, 0.9],
        message: 'THE ENTIRE COLD AISLE GOES BLACK',
        duration: 1.25,
        cue: 'fluorescent-dropout',
        effect: { flicker: 1.5, silence: 1.4 },
      },
    ],
  },
  equipment: {
    flashlight: {
      color: 0xc0e8f4,
      intensity: 54,
      distance: 18.5,
      angle: 0.39,
      drainPerSecond: 0.006,
      emergencyRechargePerSecond: 0.0019,
      flashCost: 0.31,
    },
  },
  evidence: {
    recharge: 0.3,
    entries: [
      'SYSLOG 04 / HEAT SIGNATURE MATCHES THE PREVIOUS TECH',
      'SYSLOG 12 / FANS TRACK MOTION WITH NO SENSORS',
      'SYSLOG 21 / THE SHAFT OPENS INTO AN OLDER RACK',
    ],
  },
  monster: {
    name: 'The Operator',
    identity: 'foreman',
    presentation: {
      silhouette: 'asymmetric-maintenance-husk',
      eyePulse: 0.55,
      twitchStrength: 0.85,
    },
    sound: {
      breathPitch: 0.8,
      breathWeight: 0.88,
      stepWeight: 1.15,
      drag: 0.12,
    },
    skin: {
      type: 'maintenance-husk',
      body: 0x0c1418,
      accent: 0x3a90a8,
      eye: 0x7ad8f0,
      emissiveIntensity: 2.1,
      scale: 1.1,
    },
    timing: {
      firstScare: [12, 22],
      scareInterval: [14, 28],
      firstChase: [46, 66],
      glimpseDuration: 1.2,
      stalkDuration: 23,
      pathRefresh: { stalk: 0.65, chase: 0.32 },
    },
    behavior: {
      sight: { range: 24, peripheralDot: 0.22, acquireRate: 1.38, threshold: 0.44 },
      hearing: { baseCells: 3, noiseCells: 11, chaseNoise: 0.68, reacquireNoise: 0.4 },
      chase: { lostSightDelay: 5.8, searchDuration: [9, 14], recovery: [18, 28] },
      wanderCells: [3, 7],
    },
    speeds: { watched: 0.36, stalk: 1.18, chase: 3.45 },
    stalkTriggerDistance: 10.8,
    catchDistance: 0.94,
  },
};
