// Auto-discovered campaign chapter; keep this module data-only and deterministic.
export default {
  id: 'hospital-ward',
  index: 7,
  name: 'Hospital Ward',
  exit: { label: 'FIRE DOOR' },
  copy: {
    classification: 'THRESHOLD ARCHIVE / LEVEL 7',
    status: 'WARD EVACUATION INCOMPLETE',
    start: {
      kicker: 'NIGHT WARD / BED COUNT UNKNOWN',
      title: 'THE MONITORS<br />KNOW YOUR PULSE.',
      body: 'Close three oxygen valves. Empty beds keep pressing their call buttons.',
      button: 'ENTER LEVEL 7',
    },
    pause: {
      kicker: 'OBSERVATION SUSPENDED',
      title: 'PLEASE REMAIN<br />STILL.',
      body: 'A chart at the nurses station is already recording your symptoms.',
      button: 'RESUME OBSERVATION',
    },
    death: {
      kicker: 'TIME OF DEATH OMITTED',
      title: 'BED<br />ASSIGNED.',
      body: 'The ward adds your room to a corridor that was not there before.',
      button: 'READMIT',
    },
    win: {
      kicker: 'FIRE DOOR UNSEALED',
      title: 'DISCHARGE<br />DENIED.',
      body: 'The stairwell descends into concrete and exhaust fumes.',
      button: 'DESCEND TO LEVEL 8',
    },
  },
  maze: {
    desktop: { cols: 21, rows: 27 },
    mobile: { cols: 17, rows: 21 },
    loopRatio: 0.17,
    roomDivisor: 55,
    minimumRooms: 8,
    roomSize: { min: 2, max: 4 },
    seedSalt: 0x7eaf110d,
  },
  surfaces: {
    wall: {
      base: [178, 193, 184],
      accent: [111, 139, 128],
      grime: [57, 76, 69],
      pattern: 'painted-concrete',
      roughness: 0.74,
      metalness: 0.01,
      bumpScale: 0.03,
      grimeOpacity: 0.15,
    },
    floor: {
      base: [135, 151, 145],
      accent: [89, 111, 104],
      grime: [48, 63, 58],
      pattern: 'flooded-concrete',
      roughness: 0.4,
      metalness: 0.04,
      bumpScale: 0.018,
    },
    ceiling: {
      base: [193, 202, 195],
      accent: [143, 158, 150],
      grime: [82, 99, 92],
      pattern: 'service-slab',
      roughness: 0.86,
      metalness: 0.02,
      bumpScale: 0.032,
      emissive: 0x33483f,
      emissiveIntensity: 0.3,
    },
    trim: { color: 0x54766c, roughness: 0.66, metalness: 0.18 },
  },
  fog: { color: 0x718c80, density: { desktop: 0.031, mobile: 0.037 } },
  lighting: {
    exposure: 0.88,
    hemisphere: {
      sky: 0xd8f0e7,
      ground: 0x18241f,
      intensity: { desktop: 0.57, mobile: 0.65 },
    },
    ambient: { color: 0x8fb6a8, intensity: { desktop: 0.25, mobile: 0.32 } },
    fixture: {
      color: 0xe2fff3,
      panelColor: 0xecfff7,
      deadPanelColor: 0x40554d,
      intensity: 102,
      distance: 11.5,
      angle: 1.18,
      penumbra: 0.92,
      decay: 2,
      brokenChance: 0.22,
      pool: { desktop: 7, mobile: 4 },
      flicker: { idleRate: 4.6, idleDepth: 0.026, faultFloor: 0.018, recovery: 0.38 },
    },
  },
  audio: {
    drips: true,
    masterGain: 0.68,
    humGain: 0.044,
    oscillators: [
      { frequency: 50, type: 'sine', gain: 0.18 },
      { frequency: 100, type: 'triangle', gain: 0.028 },
      { frequency: 25, type: 'sine', gain: 0.09 },
    ],
    noise: { filter: 'highpass', frequency: 680, q: 0.4, gain: 0.022 },
    heartbeat: { startFrequency: 72, endFrequency: 38 },
    impact: { startFrequency: 52, endFrequency: 20 },
    footstep: { walkLowpass: 285, runLowpass: 365 },
    ambience: {
      interval: [8, 19],
      cues: ['distant-ring', 'near-drip', 'drain-breath', 'fluorescent-dropout'],
      stereoWidth: 0.86,
      silenceChance: 0.18,
    },
  },
  objective: {
    type: 'valve',
    count: 3,
    color: 0x71c7ab,
    labels: {
      hud: 'ISOLATE THE OXYGEN LINES',
      item: 'OXYGEN VALVE',
      itemPlural: 'OXYGEN VALVES',
      interact: 'E  CLOSE VALVE',
      progress: 'LINES ISOLATED {current}/{total}',
      locked: 'FIRE DOOR PRESSURE-SEALED',
      complete: 'OXYGEN ISOLATED / FIND FIRE DOOR',
    },
  },
  props: [
    { type: 'wall-pipe', density: 0.082, color: 0xd3ded9, accent: 0x4c7568, cluster: [2, 5] },
    { type: 'hospital-bed', density: 0.028, color: 0x507568, accent: 0xc2d6ce, cluster: [1, 4] },
    { type: 'ceiling-vent', density: 0.052, color: 0x879c94, accent: 0x3f514a, cluster: [1, 3] },
    { type: 'standing-water', density: 0.038, color: 0x587d73, accent: 0xb0d8ca, cluster: [1, 4] },
    { type: 'hanging-chain', density: 0.018, color: 0x637a73, accent: 0x263832, cluster: [1, 2] },
  ],
  incidents: {
    density: 0.014,
    minCount: 3,
    maxCount: 7,
    minCellDistance: 3,
    weights: {
      'collapsed-wanderer': 1.7,
      'abandoned-pack': 1.1,
      'chair-pile': 0.9,
      'black-motes': 0.8,
      'shoe-trail': 1.3,
    },
    palette: { cloth: 0xb9cbc4, clothLight: 0xe1ece7, motes: 0x14251f },
  },
  atmosphere: {
    identity: 'unoccupied-night-ward',
    cadence: { first: [7, 13], interval: [13, 23] },
    pauseDuringChase: true,
    environmentalStory: [
      { id: 'patient-board', text: 'PATIENT: YOU / CONDITION: LISTENING', density: 0.009, placement: 'wall' },
      { id: 'floor-arrow', text: 'RADIOLOGY ← / EXIT → / BOTH RETURN HERE', density: 0.008, placement: 'floor' },
      { id: 'oxygen-card', text: 'LINE PRESSURE RISES WHEN YOU BREATHE', density: 0.006, placement: 'objective' },
    ],
    milestones: [
      {
        id: 'ward-first-line',
        progress: 0.33,
        message: 'EVERY CALL LIGHT TURNS ON EXCEPT THE ONE BESIDE YOU',
        duration: 1.22,
        cue: 'distant-ring',
        effect: { flicker: 0.35 },
      },
      {
        id: 'ward-last-line',
        progress: 1,
        message: 'A MONITOR FLATLINES AT THE FAR END OF THE WARD',
        duration: 1.28,
        cue: 'machine-dropout',
        effect: { silence: 1.25 },
      },
    ],
    events: [
      {
        id: 'call-button', earliest: 5, weight: 1.35, maxRepeats: 3,
        tension: [0.02, 0.84], message: 'AN EMPTY ROOM PRESSES ITS CALL BUTTON', duration: 1.1,
        cue: 'distant-ring', pan: 'random',
      },
      {
        id: 'curtain-drawn', earliest: 15, weight: 0.88, maxRepeats: 2,
        tension: [0.08, 0.86], message: 'A CURTAIN RING SLIDES AROUND AN EMPTY BED', duration: 1.18,
        cue: 'chain-drag', pan: 'random',
      },
      {
        id: 'oxygen-breath', earliest: 25, weight: 0.64, maxRepeats: 2,
        tension: [0.16, 0.94], message: 'THE OXYGEN LINE INHALES BEFORE YOU DO', duration: 1.24,
        cue: 'drain-breath', effect: { glitch: 0.26 },
      },
      {
        id: 'ward-blackout', earliest: 38, weight: 0.42, maxRepeats: 1,
        tension: [0.25, 0.9], message: 'THE WARD GOES DARK ROOM BY ROOM', duration: 1.32,
        cue: 'fluorescent-dropout', effect: { flicker: 1.15, silence: 1.4 },
      },
    ],
  },
  equipment: {
    flashlight: {
      color: 0xe4fff5,
      intensity: 57,
      distance: 18.5,
      angle: 0.37,
      drainPerSecond: 0.0058,
      emergencyRechargePerSecond: 0.0019,
      flashCost: 0.3,
    },
  },
  evidence: {
    recharge: 0.28,
    entries: [
      'WARD NOTE 03 / THE BED RESTRAINTS CLOSE WHEN THE LIGHTS FAIL',
      'NURSE LOG 11 / NIGHT SHIFT HAS BEEN ON DUTY FOR NINE YEARS',
      'DISCHARGE FORM / DESTINATION: LOWER LEVEL / ESCORT: NONE',
    ],
  },
  monster: {
    name: 'The Attendant',
    identity: 'still',
    presentation: { silhouette: 'wire-rib-sentinel', eyePulse: 0.14, twitchStrength: 1.12 },
    sound: { breathPitch: 0.82, breathWeight: 0.62, stepWeight: 0.38, drag: 0.12 },
    skin: {
      type: 'faceless-shadow',
      body: 0x07100d,
      accent: 0x27473d,
      eye: null,
      emissiveIntensity: 0,
      scale: 1.08,
    },
    timing: {
      firstScare: [9, 16],
      scareInterval: [12, 22],
      firstChase: [40, 57],
      glimpseDuration: 1.1,
      stalkDuration: 21,
      pathRefresh: { stalk: 0.61, chase: 0.28 },
    },
    behavior: {
      sight: { range: 19, peripheralDot: 0.3, acquireRate: 1.28, threshold: 0.47 },
      hearing: { baseCells: 3.4, noiseCells: 11, chaseNoise: 0.68, reacquireNoise: 0.38 },
      chase: { lostSightDelay: 5.8, searchDuration: [9, 15], recovery: [15, 23] },
      wanderCells: [3, 7],
    },
    speeds: { watched: 0.17, stalk: 1.38, chase: 3.68 },
    stalkTriggerDistance: 10.8,
    catchDistance: 0.9,
  },
};
