// Auto-discovered campaign chapter; keep this module data-only and deterministic.
export default {
  id: 'abandoned-mall',
  index: 6,
  name: 'Abandoned Mall',
  exit: { label: 'SERVICE EXIT' },
  copy: {
    classification: 'THRESHOLD ARCHIVE / LEVEL 6',
    status: 'RETAIL GRID OFFLINE',
    start: {
      kicker: 'CONCOURSE / AFTER CLOSING',
      title: 'THE STORES<br />ARE STILL OPEN.',
      body: 'Restore four shutter fuses. The directory lists shops that were never built.',
      button: 'ENTER LEVEL 6',
    },
    pause: {
      kicker: 'SECURITY CAMERA HOLD',
      title: 'EVERY DISPLAY<br />IS WATCHING.',
      body: 'Music continues somewhere beyond the locked storefronts.',
      button: 'RETURN TO CONCOURSE',
    },
    death: {
      kicker: 'CUSTOMER COUNT UPDATED',
      title: 'ONE SHOPPER<br />REMAINS.',
      body: 'The closing announcement now uses your name.',
      button: 'REOPEN MALL',
    },
    win: {
      kicker: 'SERVICE SHUTTER RELEASED',
      title: 'THE EXIT<br />LEADS DOWN.',
      body: 'Cold antiseptic light waits below the loading stairs.',
      button: 'DESCEND TO LEVEL 7',
    },
  },
  maze: {
    desktop: { cols: 27, rows: 19 },
    mobile: { cols: 21, rows: 15 },
    loopRatio: 0.34,
    roomDivisor: 44,
    minimumRooms: 10,
    roomSize: { min: 2, max: 5 },
    seedSalt: 0x6a11c0de,
  },
  surfaces: {
    wall: {
      base: [172, 166, 148],
      accent: [117, 105, 91],
      grime: [48, 43, 39],
      pattern: 'aged-wallpaper',
      roughness: 0.84,
      metalness: 0.03,
      bumpScale: 0.045,
      grimeOpacity: 0.2,
    },
    floor: {
      base: [102, 100, 94],
      accent: [62, 68, 70],
      grime: [35, 33, 31],
      pattern: 'oil-stained-concrete',
      roughness: 0.58,
      metalness: 0.05,
      bumpScale: 0.025,
    },
    ceiling: {
      base: [181, 178, 164],
      accent: [127, 126, 116],
      grime: [72, 69, 62],
      pattern: 'acoustic-tile',
      roughness: 0.92,
      metalness: 0.01,
      bumpScale: 0.035,
      emissive: 0x3a352c,
      emissiveIntensity: 0.26,
    },
    trim: { color: 0x655f59, roughness: 0.63, metalness: 0.24 },
  },
  fog: { color: 0x655f55, density: { desktop: 0.026, mobile: 0.032 } },
  lighting: {
    exposure: 0.92,
    hemisphere: {
      sky: 0xe9d7ad,
      ground: 0x26231f,
      intensity: { desktop: 0.62, mobile: 0.7 },
    },
    ambient: { color: 0xa6977e, intensity: { desktop: 0.27, mobile: 0.34 } },
    fixture: {
      color: 0xffe7bb,
      panelColor: 0xffedc8,
      deadPanelColor: 0x4a4640,
      intensity: 108,
      distance: 13,
      angle: 1.26,
      penumbra: 0.86,
      decay: 2,
      brokenChance: 0.18,
      pool: { desktop: 8, mobile: 4 },
      flicker: { idleRate: 3.8, idleDepth: 0.035, faultFloor: 0.025, recovery: 0.31 },
    },
  },
  audio: {
    drips: false,
    masterGain: 0.72,
    humGain: 0.052,
    oscillators: [
      { frequency: 60, type: 'sine', gain: 0.2 },
      { frequency: 120, type: 'triangle', gain: 0.035 },
      { frequency: 30, type: 'sine', gain: 0.11 },
    ],
    noise: { filter: 'bandpass', frequency: 720, q: 0.7, gain: 0.028 },
    heartbeat: { startFrequency: 66, endFrequency: 35 },
    impact: { startFrequency: 46, endFrequency: 16 },
    footstep: { walkLowpass: 330, runLowpass: 420 },
    ambience: {
      interval: [11, 24],
      cues: ['distant-ring', 'ballast-pop', 'distant-knock', 'fluorescent-dropout'],
      stereoWidth: 0.94,
      silenceChance: 0.22,
    },
  },
  objective: {
    type: 'fuse',
    count: 4,
    color: 0xe0aa64,
    labels: {
      hud: 'RESTORE THE SECURITY SHUTTERS',
      item: 'SHUTTER FUSE',
      itemPlural: 'SHUTTER FUSES',
      interact: 'E  RESET FUSE',
      progress: 'SHUTTERS {current}/{total}',
      locked: 'SERVICE EXIT MAGLOCKED',
      complete: 'SHUTTERS ONLINE / FIND SERVICE EXIT',
    },
  },
  props: [
    { type: 'square-column', density: 0.024, color: 0xb3aa98, accent: 0x6f675c, cluster: [1, 3] },
    { type: 'discarded-chair', density: 0.021, color: 0x584d45, accent: 0x9a775c, cluster: [2, 6] },
    { type: 'ceiling-vent', density: 0.058, color: 0x777870, accent: 0x343631, cluster: [1, 4] },
    { type: 'retail-shelf', density: 0.016, color: 0x554f45, accent: 0xa18d65, cluster: [1, 2] },
    { type: 'cable-tray', density: 0.038, color: 0x454743, accent: 0x1f211f, cluster: [2, 5] },
  ],
  incidents: {
    density: 0.016,
    minCount: 3,
    maxCount: 8,
    minCellDistance: 4,
    weights: {
      'collapsed-wanderer': 0.7,
      'abandoned-pack': 1.8,
      'chair-pile': 1.6,
      'black-motes': 0.45,
      'shoe-trail': 1.25,
    },
    palette: { cloth: 0x4a4140, clothLight: 0x88746b, motes: 0x171412 },
  },
  atmosphere: {
    identity: 'after-hours-retail-concourse',
    cadence: { first: [9, 16], interval: [15, 27] },
    pauseDuringChase: true,
    environmentalStory: [
      { id: 'directory', text: 'YOU ARE HERE / STORE LOCATION REMOVED', density: 0.01, placement: 'wall' },
      { id: 'sale-tag', text: 'FINAL CLEARANCE / NO RETURNS AFTER CLOSING', density: 0.007, placement: 'floor' },
      { id: 'security-count', text: 'OCCUPANCY: 2 / CAMERAS: 0', density: 0.006, placement: 'objective' },
    ],
    milestones: [
      {
        id: 'mall-half-lit',
        progress: 0.5,
        message: 'HALF THE STOREFRONTS RAISE THEIR SHUTTERS AT ONCE',
        duration: 1.25,
        cue: 'relay-chatter',
        effect: { flicker: 0.45 },
      },
      {
        id: 'mall-last-call',
        progress: 1,
        message: 'THE CLOSING ANNOUNCEMENT WHISPERS YOUR NAME',
        duration: 1.3,
        cue: 'distant-ring',
        effect: { silence: 1.15 },
      },
    ],
    events: [
      {
        id: 'escalator-step', earliest: 7, weight: 1.2, maxRepeats: 3,
        tension: [0.02, 0.86], message: 'AN ESCALATOR TAKES ONE STEP', duration: 1.05,
        cue: 'machine-dropout', pan: 'random',
      },
      {
        id: 'store-phone', earliest: 16, weight: 0.9, maxRepeats: 2,
        tension: [0.08, 0.82], message: 'A PHONE RINGS BEHIND A SEALED SHUTTER', duration: 1.2,
        cue: 'distant-ring', pan: 'random',
      },
      {
        id: 'mannequin-turn', earliest: 27, weight: 0.62, maxRepeats: 2,
        tension: [0.18, 0.92], message: 'DISPLAY SHADOWS TURN TOWARD THE CONCOURSE', duration: 1.22,
        cue: 'fluorescent-dropout', effect: { glitch: 0.3 },
      },
      {
        id: 'closing-time', earliest: 39, weight: 0.46, maxRepeats: 1,
        tension: [0.26, 0.9], message: 'ALL MUSIC STOPS BETWEEN THE SAME TWO NOTES', duration: 1.28,
        cue: 'ballast-pop', effect: { flicker: 1.0, silence: 1.5 },
      },
    ],
  },
  equipment: {
    flashlight: {
      color: 0xffe2b5,
      intensity: 55,
      distance: 20,
      angle: 0.42,
      drainPerSecond: 0.0054,
      emergencyRechargePerSecond: 0.002,
      flashCost: 0.29,
    },
  },
  evidence: {
    recharge: 0.3,
    entries: [
      'SECURITY LOG 06 / CAMERAS TRACK A CUSTOMER WITH NO REFLECTION',
      'LEASE FILE 19 / EVERY TENANT SIGNED THE SAME HANDWRITING',
      'CLOSING REPORT / THE MALL HAS NO EXTERIOR DOORS',
    ],
  },
  monster: {
    name: 'The Display',
    identity: 'still',
    presentation: { silhouette: 'wire-rib-sentinel', eyePulse: 0.08, twitchStrength: 0.82 },
    sound: { breathPitch: 0.68, breathWeight: 0.32, stepWeight: 0.58, drag: 0.18 },
    skin: {
      type: 'faceless-shadow',
      body: 0x080706,
      accent: 0x2d2722,
      eye: null,
      emissiveIntensity: 0,
      scale: 1.04,
    },
    timing: {
      firstScare: [12, 20],
      scareInterval: [14, 27],
      firstChase: [46, 64],
      glimpseDuration: 1.35,
      stalkDuration: 23,
      pathRefresh: { stalk: 0.68, chase: 0.31 },
    },
    behavior: {
      sight: { range: 24, peripheralDot: 0.22, acquireRate: 1.08, threshold: 0.52 },
      hearing: { baseCells: 2.5, noiseCells: 9, chaseNoise: 0.76, reacquireNoise: 0.42 },
      chase: { lostSightDelay: 5.4, searchDuration: [8, 14], recovery: [17, 26] },
      wanderCells: [4, 9],
    },
    speeds: { watched: 0.2, stalk: 1.28, chase: 3.62 },
    stalkTriggerDistance: 12.5,
    catchDistance: 0.91,
  },
};
