// Auto-discovered campaign chapter; keep this module data-only and deterministic.
export default {
  id: 'empty-supermarket',
  index: 13,
  name: 'Empty Supermarket',
  exit: { label: 'LOADING BAY' },
  copy: {
    classification: 'THRESHOLD ARCHIVE / LEVEL 13',
    status: 'STORE OPEN / INVENTORY ZERO',
    start: {
      kicker: 'AISLE NETWORK / OPEN 24 HOURS',
      title: 'EVERY SHELF<br />IS FACING YOU.',
      body: 'Reset four checkout fuses. The public address system is counting your steps.',
      button: 'ENTER LEVEL 13',
    },
    pause: {
      kicker: 'PRICE CHECK SUSPENDED',
      title: 'PLEASE WAIT<br />IN YOUR AISLE.',
      body: 'Cart wheels turn slowly beyond the endcaps.',
      button: 'CONTINUE SHOPPING',
    },
    death: {
      kicker: 'UNSCANNED ITEM DETECTED',
      title: 'CLEANUP<br />REQUESTED.',
      body: 'A receipt prints one line: CUSTOMER WILL REMAIN IN STORE.',
      button: 'REOPEN REGISTER',
    },
    win: {
      kicker: 'LOADING BAY UNLOCKED',
      title: 'THE DELIVERY<br />GOES DOWN.',
      body: 'The freight ramp drops toward another fluorescent horizon.',
      button: 'DESCEND TO LEVEL 14',
    },
  },
  maze: {
    desktop: { cols: 33, rows: 23 },
    mobile: { cols: 25, rows: 17 },
    loopRatio: 0.33,
    roomDivisor: 45,
    minimumRooms: 12,
    roomSize: { min: 3, max: 6 },
    seedSalt: 0xd5a9e713,
  },
  surfaces: {
    wall: {
      base: [181, 184, 171],
      accent: [93, 124, 132],
      grime: [58, 63, 59],
      pattern: 'aged-wallpaper',
      roughness: 0.79,
      metalness: 0.02,
      bumpScale: 0.038,
      grimeOpacity: 0.16,
    },
    floor: {
      base: [125, 132, 130],
      accent: [78, 91, 94],
      grime: [43, 48, 47],
      pattern: 'oil-stained-concrete',
      roughness: 0.5,
      metalness: 0.06,
      bumpScale: 0.022,
    },
    ceiling: {
      base: [192, 195, 182],
      accent: [144, 150, 141],
      grime: [82, 88, 82],
      pattern: 'acoustic-tile',
      roughness: 0.9,
      metalness: 0.01,
      bumpScale: 0.032,
      emissive: 0x3d4643,
      emissiveIntensity: 0.31,
    },
    trim: { color: 0x52727a, roughness: 0.57, metalness: 0.28 },
  },
  fog: { color: 0x77817d, density: { desktop: 0.025, mobile: 0.031 } },
  lighting: {
    exposure: 0.97,
    hemisphere: {
      sky: 0xe4f4ef,
      ground: 0x202725,
      intensity: { desktop: 0.67, mobile: 0.75 },
    },
    ambient: { color: 0xa5bbb5, intensity: { desktop: 0.29, mobile: 0.36 } },
    fixture: {
      color: 0xe8fff8,
      panelColor: 0xf0fffb,
      deadPanelColor: 0x4b5552,
      intensity: 112,
      distance: 13.5,
      angle: 1.26,
      penumbra: 0.93,
      decay: 2,
      brokenChance: 0.16,
      pool: { desktop: 9, mobile: 5 },
      flicker: { idleRate: 5.3, idleDepth: 0.022, faultFloor: 0.026, recovery: 0.29 },
    },
  },
  audio: {
    drips: false,
    masterGain: 0.69,
    humGain: 0.047,
    oscillators: [
      { frequency: 60, type: 'sine', gain: 0.18 },
      { frequency: 120, type: 'triangle', gain: 0.03 },
      { frequency: 30, type: 'sine', gain: 0.085 },
      { frequency: 240, type: 'sine', gain: 0.009 },
    ],
    noise: { filter: 'bandpass', frequency: 640, q: 0.62, gain: 0.024 },
    heartbeat: { startFrequency: 69, endFrequency: 36 },
    impact: { startFrequency: 50, endFrequency: 18 },
    footstep: { walkLowpass: 315, runLowpass: 400 },
    ambience: {
      interval: [9, 22],
      cues: ['distant-ring', 'ballast-pop', 'machine-dropout', 'pressure-groan'],
      stereoWidth: 0.93,
      silenceChance: 0.21,
    },
  },
  objective: {
    type: 'fuse',
    count: 4,
    color: 0x79b8c6,
    labels: {
      hud: 'RESTORE THE CHECKOUT CIRCUITS',
      item: 'REGISTER FUSE',
      itemPlural: 'REGISTER FUSES',
      interact: 'E  RESET REGISTER',
      progress: 'REGISTERS {current}/{total}',
      locked: 'LOADING BAY SHUTTER OFFLINE',
      complete: 'CHECKOUTS ONLINE / FIND LOADING BAY',
    },
  },
  props: [
    { type: 'square-column', density: 0.018, color: 0xaab0a5, accent: 0x55747b, cluster: [1, 3] },
    { type: 'retail-shelf', density: 0.025, color: 0x5a615b, accent: 0x98a897, cluster: [2, 6] },
    { type: 'discarded-chair', density: 0.014, color: 0x4f5f62, accent: 0x83a0a6, cluster: [1, 4] },
    { type: 'ceiling-vent', density: 0.06, color: 0x858f8b, accent: 0x3e4946, cluster: [1, 4] },
    { type: 'standing-water', density: 0.044, color: 0x526e6d, accent: 0xb0ceca, cluster: [1, 5] },
    { type: 'cable-tray', density: 0.032, color: 0x58615f, accent: 0x252c2a, cluster: [1, 4] },
  ],
  incidents: {
    density: 0.016,
    minCount: 4,
    maxCount: 9,
    minCellDistance: 4,
    weights: {
      'collapsed-wanderer': 0.65,
      'abandoned-pack': 2,
      'chair-pile': 0.75,
      'black-motes': 0.8,
      'shoe-trail': 1.75,
    },
    palette: { cloth: 0x4d6668, clothLight: 0x91aaab, motes: 0x101716 },
  },
  atmosphere: {
    identity: 'open-all-night-empty-market',
    cadence: { first: [8, 15], interval: [14, 26] },
    pauseDuringChase: true,
    environmentalStory: [
      { id: 'aisle-sign', text: 'AISLE ∞ / HOUSEHOLD / PERSONAL / LOST', density: 0.01, placement: 'wall' },
      { id: 'spill-marker', text: 'CLEANUP REQUIRED WHERE SHADOW WAS FOUND', density: 0.007, placement: 'floor' },
      { id: 'register-screen', text: 'CUSTOMERS IN STORE: 2 / CARTS: 1', density: 0.006, placement: 'objective' },
    ],
    milestones: [
      {
        id: 'market-two-registers',
        progress: 0.5,
        message: 'SCANNERS BEEP DOWN EVERY CHECKOUT LANE',
        duration: 1.2,
        cue: 'distant-ring',
        effect: { flicker: 0.34 },
      },
      {
        id: 'market-all-registers',
        progress: 1,
        message: 'A RECEIPT PRINTS THE ROUTE TO THE LOADING BAY',
        duration: 1.28,
        cue: 'relay-chatter',
        effect: { glitch: 0.27, silence: 1.05 },
      },
    ],
    events: [
      {
        id: 'cart-wheel', earliest: 6, weight: 1.25, maxRepeats: 3,
        tension: [0.02, 0.86], message: 'A CART WITH ONE BAD WHEEL CROSSES THE NEXT AISLE', duration: 1.1,
        cue: 'chain-drag', pan: 'random',
      },
      {
        id: 'price-check', earliest: 15, weight: 0.92, maxRepeats: 2,
        tension: [0.08, 0.85], message: 'PRICE CHECK REQUESTED FOR THE SOUND OF BREATHING', duration: 1.2,
        cue: 'distant-ring', pan: 'random',
      },
      {
        id: 'freezer-open', earliest: 26, weight: 0.66, maxRepeats: 2,
        tension: [0.16, 0.93], message: 'A FREEZER DOOR OPENS INTO A WARM, DARK ROOM', duration: 1.24,
        cue: 'pressure-groan', effect: { glitch: 0.29 },
      },
      {
        id: 'store-closing', earliest: 40, weight: 0.43, maxRepeats: 1,
        tension: [0.27, 0.91], message: 'THE STORE ANNOUNCES IT WILL NEVER CLOSE', duration: 1.32,
        cue: 'ballast-pop', effect: { flicker: 1.1, silence: 1.45 },
      },
    ],
  },
  equipment: {
    flashlight: {
      color: 0xe4fff9,
      intensity: 54,
      distance: 21,
      angle: 0.41,
      drainPerSecond: 0.0051,
      emergencyRechargePerSecond: 0.0021,
      flashCost: 0.28,
    },
  },
  evidence: {
    recharge: 0.31,
    entries: [
      'REGISTER TAPE 13 / ITEM: CUSTOMER / PRICE: ONE EXIT',
      'STOCK LOG / EVERY SHELF RESTOCKS WITH EMPTY PACKAGING',
      'PA RECORDING / PLEASE BRING THE UNATTENDED SHADOW TO CHECKOUT',
    ],
  },
  monster: {
    name: 'The Stocker',
    identity: 'foreman',
    presentation: { silhouette: 'asymmetric-maintenance-husk', eyePulse: 0.44, twitchStrength: 0.8 },
    sound: { breathPitch: 0.61, breathWeight: 0.68, stepWeight: 0.82, drag: 0.38 },
    skin: {
      type: 'maintenance-husk',
      body: 0x070b0a,
      accent: 0x31545b,
      eye: 0xb8f2ff,
      emissiveIntensity: 0.42,
      scale: 1.12,
    },
    timing: {
      firstScare: [11, 18],
      scareInterval: [14, 25],
      firstChase: [44, 61],
      glimpseDuration: 1.2,
      stalkDuration: 22,
      pathRefresh: { stalk: 0.58, chase: 0.27 },
    },
    behavior: {
      sight: { range: 26, peripheralDot: 0.19, acquireRate: 1.3, threshold: 0.47 },
      hearing: { baseCells: 3.8, noiseCells: 12, chaseNoise: 0.65, reacquireNoise: 0.36 },
      chase: { lostSightDelay: 5.7, searchDuration: [9, 16], recovery: [15, 24] },
      wanderCells: [5, 10],
    },
    speeds: { watched: 0.45, stalk: 1.4, chase: 3.78 },
    stalkTriggerDistance: 12.8,
    catchDistance: 0.94,
  },
};
