// Auto-discovered campaign chapter; keep this module data-only and deterministic.
export default {
  id: 'level-5',
  index: 5,
  name: 'Cold Storage',
  exit: { label: 'LOCK' },
  copy: {
    classification: 'THRESHOLD ARCHIVE / LEVEL 5',
    status: 'REFRIGERATION OVERRIDE',
    start: {
      kicker: 'FREEZER WING / DEPTH UNMARKED',
      title: 'BREATH STAYS<br />IN THE AIR.',
      body: 'Open three pressure valves. Frost keeps forming footprints that are not yours.',
      button: 'ENTER LEVEL 5',
    },
    pause: {
      kicker: 'THERMAL FEED LOST',
      title: 'DO NOT<br />EXHALE.',
      body: 'Your breath hangs in the frame long after you stop moving.',
      button: 'THAW',
    },
    death: {
      kicker: 'CORE TEMPERATURE CRITICAL',
      title: 'FROZEN<br />IN PLACE.',
      body: 'Recovery found a second outline melted into the frost beside yours.',
      button: 'DEFROST CYCLE',
    },
    win: {
      kicker: 'OUTER LOCK CYCLES',
      title: 'THE COLD<br />HAS A DOOR.',
      body: 'Warm yellow light spills through the LOCK. The carpet beyond is already damp.',
      button: 'RETURN TO LEVEL 0',
    },
  },
  maze: {
    desktop: { cols: 17, rows: 25 },
    mobile: { cols: 15, rows: 19 },
    loopRatio: 0.16,
    roomDivisor: 64,
    minimumRooms: 5,
    roomSize: { min: 2, max: 4 },
    seedSalt: 0xd3a2646c,
  },
  surfaces: {
    wall: {
      base: [118, 138, 148],
      accent: [88, 110, 122],
      grime: [48, 62, 72],
      pattern: 'seeping-concrete',
      roughness: 0.7,
      metalness: 0.06,
      bumpScale: 0.07,
      grimeOpacity: 0.2,
    },
    floor: {
      base: [92, 112, 122],
      accent: [68, 88, 98],
      grime: [40, 54, 62],
      pattern: 'flooded-concrete',
      roughness: 0.38,
      metalness: 0.08,
      bumpScale: 0.022,
    },
    ceiling: {
      base: [102, 122, 132],
      accent: [74, 94, 104],
      grime: [42, 56, 64],
      pattern: 'dripping-concrete',
      roughness: 0.88,
      metalness: 0.04,
      bumpScale: 0.06,
      emissive: 0x142028,
      emissiveIntensity: 0.14,
    },
    trim: { color: 0x4a6470, roughness: 0.72, metalness: 0.22 },
  },
  fog: {
    color: 0x243840,
    density: { desktop: 0.05, mobile: 0.058 },
  },
  lighting: {
    exposure: 0.62,
    hemisphere: {
      sky: 0x90b8c8,
      ground: 0x101820,
      intensity: { desktop: 0.32, mobile: 0.4 },
    },
    ambient: {
      color: 0x4a7080,
      intensity: { desktop: 0.12, mobile: 0.18 },
    },
    fixture: {
      color: 0xc8e8f4,
      panelColor: 0xd8f0f8,
      deadPanelColor: 0x2a3c44,
      intensity: 68,
      distance: 9.4,
      angle: 1.1,
      penumbra: 0.9,
      decay: 2,
      brokenChance: 0.28,
      pool: { desktop: 5, mobile: 3 },
      flicker: {
        idleRate: 2.6,
        idleDepth: 0.05,
        faultFloor: 0.01,
        recovery: 0.48,
      },
    },
  },
  audio: {
    drips: true,
    masterGain: 0.77,
    humGain: 0.058,
    oscillators: [
      { frequency: 38, type: 'sine', gain: 0.3 },
      { frequency: 76, type: 'triangle', gain: 0.05 },
      { frequency: 19, type: 'sine', gain: 0.18 },
      { frequency: 152, type: 'sine', gain: 0.01 },
    ],
    noise: { filter: 'lowpass', frequency: 240, q: 0.5, gain: 0.048 },
    heartbeat: { startFrequency: 56, endFrequency: 30 },
    impact: { startFrequency: 36, endFrequency: 12 },
    footstep: { walkLowpass: 160, runLowpass: 220 },
    ambience: {
      interval: [9, 20],
      cues: ['near-drip', 'pressure-groan', 'drain-breath', 'chain-drag'],
      stereoWidth: 0.97,
      silenceChance: 0.16,
    },
  },
  objective: {
    type: 'valve',
    count: 3,
    color: 0x7ec8d8,
    labels: {
      hud: 'THE COLD IS PRESSURIZED',
      item: 'VALVE',
      itemPlural: 'VALVES',
      interact: 'E  OPEN VALVE',
      progress: 'VALVES {current}/{total}',
      locked: 'THE LOCK WILL NOT CYCLE',
      complete: 'PRESSURE FALLS / FIND THE LOCK',
    },
  },
  props: [
    { type: 'hanging-chain', density: 0.04, color: 0x5a7078, accent: 0x243038, cluster: [1, 4] },
    { type: 'standing-water', density: 0.12, color: 0x3a5a68, accent: 0x8ab8c8, cluster: [2, 6] },
    { type: 'wall-pipe', density: 0.1, color: 0x4a646c, accent: 0x243038, cluster: [2, 4] },
    { type: 'drain-grate', density: 0.035, color: 0x2a3c44, accent: 0x12181c, cluster: [1, 2] },
    { type: 'oil-drum', density: 0.018, color: 0x4a5c64, accent: 0x6a90a0, cluster: [1, 2] },
  ],
  incidents: {
    density: 0.017,
    minCount: 3,
    maxCount: 8,
    minCellDistance: 3,
    weights: {
      'collapsed-wanderer': 1.1,
      'abandoned-pack': 0.7,
      'chair-pile': 0.35,
      'black-motes': 2.0,
      'shoe-trail': 1.8,
    },
    palette: { cloth: 0x2a3c44, clothLight: 0x4a6470, motes: 0x060c10 },
  },
  atmosphere: {
    identity: 'impossible-cold-storage',
    cadence: { first: [10, 18], interval: [14, 28] },
    pauseDuringChase: true,
    environmentalStory: [
      { id: 'temp-gauge', text: 'CORE TEMP −18°C / SURFACE TEMP BODY HEAT', density: 0.01, placement: 'wall' },
      { id: 'frost-arrow', text: 'FROST GROWS ← AGAINST AIRFLOW', density: 0.008, placement: 'floor' },
      { id: 'manifest', text: 'MANIFEST: 1 LIVING / 1 UNACCOUNTED', density: 0.005, placement: 'objective' },
    ],
    milestones: [
      {
        id: 'frost-breath',
        progress: 0.33,
        message: 'YOUR BREATH FREEZES BEFORE IT LEAVES YOU',
        duration: 1.2,
        cue: 'pressure-groan',
      },
      {
        id: 'extra-print',
        progress: 0.66,
        message: 'A SECOND SET OF PRINTS FORMS AHEAD OF YOURS',
        duration: 1.25,
        cue: 'near-drip',
        effect: { flicker: 0.55 },
      },
    ],
    events: [
      {
        id: 'frost-crack',
        earliest: 6,
        weight: 1.25,
        maxRepeats: 3,
        tension: [0.04, 0.88],
        message: 'FROST CRACKS IN A LINE TOWARD YOU',
        duration: 1.08,
        cue: 'pressure-groan',
        pan: 'random',
      },
      {
        id: 'chain-rattle',
        earliest: 14,
        weight: 0.9,
        maxRepeats: 2,
        tension: [0.1, 0.84],
        message: 'A CHAIN RATTLES WITH NO WEIGHT ON IT',
        duration: 1.12,
        cue: 'chain-drag',
        pan: 'random',
      },
      {
        id: 'melt-print',
        earliest: 22,
        weight: 0.75,
        maxRepeats: 2,
        tension: [0.16, 0.86],
        message: 'FOOTPRINTS MELT IN THE WRONG ORDER',
        duration: 1.18,
        cue: 'near-drip',
        effect: { glitch: 0.36 },
      },
      {
        id: 'freezer-exhale',
        earliest: 30,
        weight: 0.68,
        maxRepeats: 1,
        tension: [0.2, 0.8],
        message: 'THE FREEZER EXHALES WARM AIR ONCE',
        duration: 1.2,
        cue: 'drain-breath',
        pan: 'random',
      },
      {
        id: 'total-still',
        earliest: 40,
        weight: 0.45,
        maxRepeats: 1,
        tension: [0.28, 0.9],
        message: 'EVERY DROPLET STOPS MID-FALL',
        duration: 1.25,
        cue: 'water-dropout',
        effect: { flicker: 1.0, silence: 1.6 },
      },
    ],
  },
  equipment: {
    flashlight: {
      color: 0xd0eef8,
      intensity: 58,
      distance: 19.5,
      angle: 0.36,
      drainPerSecond: 0.0066,
      emergencyRechargePerSecond: 0.0017,
      flashCost: 0.33,
    },
  },
  evidence: {
    recharge: 0.26,
    entries: [
      'COLD LOG 01 / FROST FORMS FACES WHEN UNWATCHED',
      'COLD LOG 07 / THE LOCK OPENS INTO YESTERDAY\'S LOBBY',
      'COLD LOG 13 / YOUR BREATH HAS A SECOND RHYTHM',
    ],
  },
  monster: {
    name: 'The Frostbound',
    identity: 'wader',
    presentation: {
      silhouette: 'waterlogged-dragger',
      eyePulse: 0.62,
      twitchStrength: 0.55,
    },
    sound: {
      breathPitch: 0.5,
      breathWeight: 1.05,
      stepWeight: 0.95,
      drag: 0.64,
    },
    skin: {
      type: 'waterlogged-longlimb',
      body: 0x0a1418,
      accent: 0x4a7888,
      eye: 0xb8e8f8,
      emissiveIntensity: 0.7,
      scale: 1.2,
    },
    timing: {
      firstScare: [10, 18],
      scareInterval: [12, 24],
      firstChase: [38, 55],
      glimpseDuration: 1.1,
      stalkDuration: 20,
      pathRefresh: { stalk: 0.52, chase: 0.26 },
    },
    behavior: {
      sight: { range: 16, peripheralDot: 0.14, acquireRate: 1.55, threshold: 0.4 },
      hearing: { baseCells: 4, noiseCells: 13, chaseNoise: 0.58, reacquireNoise: 0.32 },
      chase: { lostSightDelay: 6.5, searchDuration: [10, 16], recovery: [14, 22] },
      wanderCells: [3, 8],
    },
    speeds: { watched: 0.52, stalk: 1.35, chase: 3.7 },
    stalkTriggerDistance: 11.6,
    catchDistance: 0.98,
  },
};
