export default {
    id: 'level-2',
    index: 2,
    name: 'Lower Tunnels',
    exit: { label: 'HATCH' },
    copy: {
      classification: 'THRESHOLD ARCHIVE / LEVEL 2',
      status: 'FLOOD CONTROL FAILURE',
      start: {
        kicker: 'LOWER ACCESS / DEPTH UNKNOWN',
        title: 'THE WATER<br />IS RISING.',
        body: 'Open four drain valves. Ignore splashing that keeps pace when you stop moving.',
        button: 'ENTER LEVEL 2',
      },
      pause: {
        kicker: 'CAMERA SUBMERGED',
        title: 'HOLD YOUR<br />BREATH.',
        body: 'Ripples continue across the feed while you are standing still.',
        button: 'SURFACE',
      },
      death: {
        kicker: 'DEPTH SENSOR OFFLINE',
        title: 'PULLED<br />UNDER.',
        body: 'The tunnel is only ankle-deep. Recovery divers found no bottom.',
        button: 'WADE BACK IN',
      },
      win: {
        kicker: 'DRAIN CYCLE COMPLETE',
        title: 'DAYLIGHT<br />IS A RECORDING.',
        body: 'A steel hatch opens above you. The birds repeat every seven seconds.',
        button: 'DESCEND TO LEVEL 3',
      },
    },
    maze: {
      desktop: { cols: 19, rows: 23 },
      mobile: { cols: 15, rows: 19 },
      loopRatio: 0.18,
      roomDivisor: 72,
      minimumRooms: 6,
      roomSize: { min: 2, max: 3 },
      seedSalt: 0xc2b2ae35,
    },
    surfaces: {
      wall: {
        base: [76, 91, 88],
        accent: [48, 66, 65],
        grime: [24, 39, 38],
        pattern: 'seeping-concrete',
        roughness: 0.96,
        metalness: 0.01,
        bumpScale: 0.082,
        grimeOpacity: 0.27,
      },
      floor: {
        base: [47, 59, 58],
        accent: [32, 45, 45],
        grime: [18, 30, 29],
        pattern: 'flooded-concrete',
        roughness: 0.46,
        metalness: 0.03,
        bumpScale: 0.028,
      },
      ceiling: {
        base: [61, 73, 70],
        accent: [39, 52, 51],
        grime: [21, 34, 33],
        pattern: 'dripping-concrete',
        roughness: 0.97,
        metalness: 0.01,
        bumpScale: 0.076,
        emissive: 0x121d1c,
        emissiveIntensity: 0.12,
      },
      trim: { color: 0x344b49, roughness: 0.9, metalness: 0.08 },
    },
    fog: {
      color: 0x1d3030,
      density: { desktop: 0.046, mobile: 0.055 },
    },
    lighting: {
      exposure: 0.65,
      hemisphere: {
        sky: 0x789893,
        ground: 0x101b1b,
        intensity: { desktop: 0.34, mobile: 0.42 },
      },
      ambient: {
        color: 0x405d5b,
        intensity: { desktop: 0.14, mobile: 0.21 },
      },
      fixture: {
        color: 0x9ac9c2,
        panelColor: 0xaed8d0,
        deadPanelColor: 0x263a39,
        intensity: 72,
        distance: 9.8,
        angle: 1.12,
        penumbra: 0.88,
        decay: 2,
        brokenChance: 0.31,
        pool: { desktop: 5, mobile: 3 },
        flicker: {
          idleRate: 3.1,
          idleDepth: 0.045,
          faultFloor: 0.012,
          recovery: 0.42,
        },
      },
    },
    audio: {
      drips: true,
      masterGain: 0.76,
      humGain: 0.062,
      oscillators: [
        { frequency: 43, type: 'sine', gain: 0.28 },
        { frequency: 86, type: 'triangle', gain: 0.058 },
        { frequency: 21, type: 'sine', gain: 0.17 },
        { frequency: 172, type: 'sine', gain: 0.014 },
      ],
      noise: { filter: 'lowpass', frequency: 290, q: 0.58, gain: 0.052 },
      heartbeat: { startFrequency: 58, endFrequency: 31 },
      impact: { startFrequency: 39, endFrequency: 14 },
      footstep: { walkLowpass: 180, runLowpass: 240 },
      ambience: {
        interval: [10, 22],
        cues: ['near-drip', 'far-splash', 'drain-breath', 'pressure-groan'],
        stereoWidth: 0.96,
        silenceChance: 0.18,
      },
    },
    objective: {
      type: 'valve',
      count: 4,
      color: 0x55b7b0,
      labels: {
        hud: 'THE WATER KEEPS RISING',
        item: 'VALVE',
        itemPlural: 'VALVES',
        interact: 'E  OPEN VALVE',
        progress: 'VALVES {current}/{total}',
        locked: 'PRESSURE WILL NOT YIELD',
        complete: 'THE WATER FALLS / FIND THE HATCH',
      },
    },
  props: [
      { type: 'wall-pipe', density: 0.18, color: 0x3c5755, accent: 0x1d302f, cluster: [2, 6] },
      { type: 'wall-pipe', density: 0.026, color: 0x69584c, accent: 0x2f2723, cluster: [1, 2] },
      { type: 'standing-water', density: 0.2, color: 0x294d4d, accent: 0x6caaa4, cluster: [3, 8] },
      { type: 'drain-grate', density: 0.043, color: 0x293a39, accent: 0x101918, cluster: [1, 3] },
    { type: 'hanging-chain', density: 0.024, color: 0x3d4c49, accent: 0x172120, cluster: [1, 3] },
  ],
  incidents: {
    density: 0.018,
    minCount: 3,
    maxCount: 8,
    minCellDistance: 3,
    weights: {
      'collapsed-wanderer': 1.2,
      'abandoned-pack': 0.9,
      'chair-pile': 0.55,
      'black-motes': 2.2,
      'shoe-trail': 1.45,
    },
    palette: { cloth: 0x263331, clothLight: 0x40514d, motes: 0x050908 },
  },
  atmosphere: {
      identity: 'impossible-flooded-infrastructure',
      cadence: { first: [12, 22], interval: [16, 30] },
      pauseDuringChase: true,
      environmentalStory: [
        { id: 'depth-gauge', text: 'DEPTH 0.18 M / ECHO RETURN 41 M', density: 0.01, placement: 'wall' },
        { id: 'flow-arrow', text: 'FLOW DIRECTION ↑', density: 0.009, placement: 'floor' },
        { id: 'diver-log', text: 'DIVE TEAM 03 ENTERED / NO DESCENT RECORDED', density: 0.005, placement: 'objective' },
      ],
      milestones: [
        {
          id: 'pressure-reversal',
          progress: 0.25,
          message: 'THE WATER BEGINS FLOWING UPHILL',
          duration: 1.2,
          cue: 'pressure-groan',
        },
        {
          id: 'extra-valve',
          progress: 0.75,
          message: 'A FIFTH VALVE OPENS SOMEWHERE BELOW',
          duration: 1.25,
          cue: 'far-splash',
          effect: { flicker: 0.65 },
        },
      ],
      events: [
        {
          id: 'matching-splash',
          earliest: 7,
          weight: 1.2,
          maxRepeats: 3,
          tension: [0.04, 0.86],
          message: 'THE SPLASHING STOPS WHEN YOU STOP',
          duration: 1.08,
          cue: 'far-splash',
          pan: 'random',
        },
        {
          id: 'drain-breath',
          earliest: 16,
          weight: 0.92,
          maxRepeats: 2,
          tension: [0.12, 0.88],
          message: 'SOMETHING EXHALES THROUGH THE DRAIN',
          duration: 1.15,
          cue: 'drain-breath',
          pan: 'random',
        },
        {
          id: 'chain-lift',
          earliest: 23,
          weight: 0.62,
          maxRepeats: 1,
          tension: [0.15, 0.76],
          message: 'A CHAIN LIFTS OUT OF THE WATER',
          duration: 1.1,
          cue: 'chain-drag',
        },
        {
          id: 'depth-return',
          earliest: 31,
          weight: 0.72,
          maxRepeats: 2,
          tension: [0.2, 0.9],
          message: 'THE ECHO RETURNS FROM BENEATH YOUR FEET',
          duration: 1.2,
          cue: 'submerged-knock',
          pan: 'random',
          effect: { glitch: 0.48 },
        },
        {
          id: 'water-still',
          earliest: 40,
          weight: 0.48,
          maxRepeats: 1,
          tension: [0.28, 0.86],
          message: 'EVERY RIPPLE GOES FLAT AT ONCE',
          duration: 1.25,
          cue: 'water-dropout',
          effect: { flicker: 0.9, silence: 1.5 },
        },
      ],
    },
    equipment: {
      flashlight: {
        color: 0xaed8d0,
        intensity: 56,
        distance: 19,
        angle: 0.38,
        drainPerSecond: 0.0064,
        emergencyRechargePerSecond: 0.0018,
        flashCost: 0.32,
      },
    },
    evidence: {
      recharge: 0.28,
      entries: [
        'DEPTH LOG 02 / THE WATER IS DEEPER WHEN UNOBSERVED',
        'DEPTH LOG 08 / SPLASHING RECORDED ABOVE THE CEILING',
        'DEPTH LOG 14 / THE HATCH OPENS INTO THE SAME TUNNEL',
      ],
    },
    monster: {
      name: 'The Wader',
      identity: 'wader',
      presentation: {
        silhouette: 'waterlogged-dragger',
        eyePulse: 0.48,
        twitchStrength: 0.66,
      },
      sound: {
        breathPitch: 0.63,
        breathWeight: 0.92,
        stepWeight: 1.08,
        drag: 0.52,
      },
      skin: {
        type: 'waterlogged-longlimb',
        body: 0x0c1918,
        accent: 0x34514d,
        eye: 0xa9d7ce,
        emissiveIntensity: 0.55,
        scale: 1.17,
      },
      timing: {
        firstScare: [12, 20],
        scareInterval: [14, 28],
        firstChase: [42, 60],
        glimpseDuration: 1.15,
        stalkDuration: 22,
        pathRefresh: { stalk: 0.58, chase: 0.28 },
      },
      behavior: {
        sight: { range: 17, peripheralDot: 0.16, acquireRate: 1.45, threshold: 0.42 },
        hearing: { baseCells: 4, noiseCells: 12, chaseNoise: 0.62, reacquireNoise: 0.34 },
        chase: { lostSightDelay: 6.2, searchDuration: [10, 15], recovery: [16, 24] },
        wanderCells: [3, 8],
      },
      speeds: { watched: 0.48, stalk: 1.28, chase: 3.55 },
      stalkTriggerDistance: 11.4,
      catchDistance: 0.96,
    },
};
