// Auto-discovered campaign chapter; keep this module data-only and deterministic.
export default {
  id: 'level-3',
  index: 3,
  name: 'Hotel Corridors',
  exit: { label: 'STAIRS' },
  copy: {
    classification: 'THRESHOLD ARCHIVE / LEVEL 3',
    status: 'GUEST SERVICES OFFLINE',
    start: {
      kicker: 'CHECK-IN WITHOUT A NAME',
      title: 'EVERY DOOR<br />IS OCCUPIED.',
      body: 'The carpet swallows footsteps. Room numbers climb past any floor this building has.',
      button: 'ENTER LEVEL 3',
    },
    pause: {
      kicker: 'DO NOT DISTURB',
      title: 'SOMEONE IS<br />STILL INSIDE.',
      body: 'The hallway camera keeps panning toward an empty door.',
      button: 'RESUME WALK',
    },
    death: {
      kicker: 'ROOM SERVICE DECLINED',
      title: 'CHECKED<br />OUT.',
      body: 'Housekeeping logged a fourth towel set for a party of one.',
      button: 'REQUEST A NEW KEY',
    },
    win: {
      kicker: 'SERVICE STAIR UNLOCKED',
      title: 'THE CARPET<br />ENDS HERE.',
      body: 'Beyond the STAIRS sign the wallpaper turns cold and the air smells like ozone.',
      button: 'DESCEND TO LEVEL 4',
    },
  },
  maze: {
    desktop: { cols: 25, rows: 17 },
    mobile: { cols: 19, rows: 15 },
    loopRatio: 0.3,
    roomDivisor: 36,
    minimumRooms: 12,
    roomSize: { min: 2, max: 5 },
    seedSalt: 0x27d4eb2f,
  },
  surfaces: {
    wall: {
      base: [148, 92, 88],
      accent: [118, 68, 64],
      grime: [52, 28, 26],
      pattern: 'aged-wallpaper',
      roughness: 0.94,
      metalness: 0,
      bumpScale: 0.042,
      grimeOpacity: 0.22,
    },
    floor: {
      base: [96, 42, 48],
      accent: [72, 28, 34],
      grime: [38, 18, 22],
      pattern: 'damp-carpet',
      roughness: 1,
      metalness: 0,
      bumpScale: 0.068,
    },
    ceiling: {
      base: [168, 152, 142],
      accent: [132, 118, 108],
      grime: [78, 64, 58],
      pattern: 'acoustic-tile',
      roughness: 0.91,
      metalness: 0,
      bumpScale: 0.032,
      emissive: 0x3a241f,
      emissiveIntensity: 0.28,
    },
    trim: { color: 0x6e3f3a, roughness: 0.9, metalness: 0.02 },
  },
  fog: {
    color: 0x5a3834,
    density: { desktop: 0.034, mobile: 0.042 },
  },
  lighting: {
    exposure: 0.78,
    hemisphere: {
      sky: 0xd4a090,
      ground: 0x241412,
      intensity: { desktop: 0.52, mobile: 0.58 },
    },
    ambient: {
      color: 0x8a554c,
      intensity: { desktop: 0.2, mobile: 0.26 },
    },
    fixture: {
      color: 0xffd4b8,
      panelColor: 0xffe0c8,
      deadPanelColor: 0x4a3530,
      intensity: 92,
      distance: 10.8,
      angle: 1.22,
      penumbra: 0.9,
      decay: 2,
      brokenChance: 0.11,
      pool: { desktop: 6, mobile: 3 },
      flicker: {
        idleRate: 3.8,
        idleDepth: 0.028,
        faultFloor: 0.02,
        recovery: 0.22,
      },
    },
  },
  audio: {
    drips: false,
    masterGain: 0.72,
    humGain: 0.07,
    oscillators: [
      { frequency: 55, type: 'sine', gain: 0.24 },
      { frequency: 110, type: 'triangle', gain: 0.055 },
      { frequency: 28, type: 'sine', gain: 0.13 },
      { frequency: 220, type: 'sine', gain: 0.012 },
    ],
    noise: { filter: 'bandpass', frequency: 480, q: 0.58, gain: 0.034 },
    heartbeat: { startFrequency: 62, endFrequency: 34 },
    impact: { startFrequency: 48, endFrequency: 16 },
    footstep: { walkLowpass: 200, runLowpass: 270 },
    ambience: {
      interval: [14, 30],
      cues: ['distant-knock', 'distant-ring', 'ballast-pop', 'fluorescent-dropout'],
      stereoWidth: 0.84,
      silenceChance: 0.4,
    },
  },
  objective: {
    type: 'none',
    count: 0,
    color: 0xc48a7a,
    labels: {
      hud: 'THE HALLWAYS CONTINUE',
      item: '',
      itemPlural: '',
      interact: 'E  OPEN',
      progress: '',
      locked: '',
      complete: 'A STAIR EXISTS',
    },
  },
  props: [
    { type: 'square-column', density: 0.04, color: 0xa8786e, accent: 0x6a443c, cluster: [1, 3] },
    { type: 'discarded-chair', density: 0.022, color: 0x5a3430, accent: 0x2a1816, cluster: [1, 2] },
    { type: 'discarded-chair', density: 0.008, color: 0x7a4a42, accent: 0x321e1a, cluster: [2, 5] },
    { type: 'ceiling-vent', density: 0.018, color: 0x6a5854, accent: 0x2a2422, cluster: [1, 2] },
  ],
  incidents: {
    density: 0.014,
    minCount: 2,
    maxCount: 7,
    minCellDistance: 3,
    weights: {
      'collapsed-wanderer': 0.7,
      'abandoned-pack': 1.4,
      'chair-pile': 2.4,
      'black-motes': 0.45,
      'shoe-trail': 1.6,
    },
    palette: { cloth: 0x4a2824, clothLight: 0x7a5048, motes: 0x120808 },
  },
  atmosphere: {
    identity: 'wrong-hotel-hospitality',
    cadence: { first: [16, 28], interval: [20, 38] },
    pauseDuringChase: true,
    environmentalStory: [
      { id: 'room-count', text: 'ROOMS 1–∞ / VACANCY: 0', density: 0.009, placement: 'wall' },
      { id: 'ice-machine', text: 'ICE MACHINE OUT OF ORDER / STILL DISPENSING', density: 0.006, placement: 'wall' },
      { id: 'checkout', text: 'CHECKOUT TIME: NEVER', density: 0.005, placement: 'exit' },
    ],
    milestones: [],
    events: [
      {
        id: 'door-latch',
        earliest: 11,
        weight: 1.15,
        maxRepeats: 3,
        tension: [0.06, 0.8],
        message: 'A DOOR LATCH CLICKS BEHIND YOU',
        duration: 1.1,
        cue: 'distant-knock',
        pan: 'random',
      },
      {
        id: 'cart-wheels',
        earliest: 19,
        weight: 0.85,
        maxRepeats: 2,
        tension: [0.12, 0.78],
        message: 'HOUSEKEEPING CART WHEELS TURN WITH NO CART',
        duration: 1.15,
        cue: 'ballast-pop',
        effect: { glitch: 0.28 },
      },
      {
        id: 'wrong-number',
        earliest: 27,
        weight: 0.7,
        maxRepeats: 1,
        tension: [0.18, 0.74],
        message: 'THE ROOM NUMBERS SKIP YOUR FLOOR',
        duration: 1.2,
        cue: 'distant-ring',
        pan: 'random',
      },
      {
        id: 'tv-static',
        earliest: 35,
        weight: 0.62,
        maxRepeats: 2,
        tension: [0.22, 0.86],
        message: 'STATIC LEAKS FROM UNDER A CLOSED DOOR',
        duration: 1.18,
        cue: 'fluorescent-dropout',
        effect: { flicker: 0.55 },
      },
      {
        id: 'lobby-music',
        earliest: 44,
        weight: 0.48,
        maxRepeats: 1,
        tension: [0.28, 0.88],
        message: 'THE LOBBY MUSIC PLAYS BACKWARDS ONCE',
        duration: 1.25,
        cue: 'sub-bass-bump',
        effect: { silence: 1.1, flicker: 0.8 },
      },
    ],
  },
  equipment: {
    flashlight: {
      color: 0xffd8c0,
      intensity: 50,
      distance: 17.5,
      angle: 0.42,
      drainPerSecond: 0.0054,
      emergencyRechargePerSecond: 0.0021,
      flashCost: 0.29,
    },
  },
  evidence: {
    recharge: 0.32,
    entries: [
      'GUEST LOG 03 / YOUR RESERVATION PREDATES THE BUILDING',
      'GUEST LOG 09 / DO NOT ANSWER KNOCKS FROM YOUR OWN ROOM',
      'GUEST LOG 17 / THE STAIRS SKIP EVERY NUMBERED FLOOR',
    ],
  },
  monster: {
    name: 'The Concierge',
    identity: 'still',
    presentation: {
      silhouette: 'wire-rib-sentinel',
      eyePulse: 0.12,
      twitchStrength: 1.1,
    },
    sound: {
      breathPitch: 0.58,
      breathWeight: 0.52,
      stepWeight: 0.48,
      drag: 0.16,
    },
    skin: {
      type: 'faceless-shadow',
      body: 0x0a0606,
      accent: 0x2a1412,
      eye: 0xffc8a8,
      emissiveIntensity: 0.35,
      scale: 1.05,
    },
    timing: {
      firstScare: [18, 32],
      scareInterval: [18, 36],
      firstChase: [58, 82],
      glimpseDuration: 1.4,
      stalkDuration: 26,
      pathRefresh: { stalk: 0.85, chase: 0.38 },
    },
    behavior: {
      sight: { range: 22, peripheralDot: 0.32, acquireRate: 1.05, threshold: 0.52 },
      hearing: { baseCells: 2, noiseCells: 7, chaseNoise: 0.8, reacquireNoise: 0.48 },
      chase: { lostSightDelay: 4.6, searchDuration: [8, 13], recovery: [22, 34] },
      wanderCells: [4, 9],
    },
    speeds: { watched: 0.18, stalk: 1.02, chase: 3.18 },
    stalkTriggerDistance: 10.2,
    catchDistance: 0.9,
  },
};
