export default {
  id: 'level-1',
  index: 1,
  name: 'Maintenance',
  exit: { label: 'LIFT' },
  copy: {
    classification: 'THRESHOLD ARCHIVE / LEVEL 1',
    status: 'AUXILIARY POWER OFFLINE',
    start: {
      kicker: 'NIGHT SHIFT / NO STAFF ASSIGNED',
      title: 'THE MACHINES<br />ARE BREATHING.',
      body: 'Three fuse boxes feed the freight lift. The work order is signed in your handwriting.',
      button: 'ENTER LEVEL 1',
    },
    pause: {
      kicker: 'FEED DESYNCHRONIZED',
      title: 'IT HEARD<br />THE SILENCE.',
      body: 'The pipes are still knocking. Something else has stopped.',
      button: 'RESTORE FEED',
    },
    death: {
      kicker: 'MAINTENANCE LOG CLOSED',
      title: 'SHIFT<br />TERMINATED.',
      body: 'A fourth set of footsteps was recorded after contact ended.',
      button: 'CLOCK IN AGAIN',
    },
    win: {
      kicker: 'FREIGHT LIFT ACTIVE',
      title: 'THE ONLY WAY<br />IS LOWER.',
      body: 'The lift stops below its final numbered floor. Cold water crosses the threshold.',
      button: 'DESCEND TO LEVEL 2',
    },
  },
  maze: {
    desktop: { cols: 23, rows: 19 },
    mobile: { cols: 19, rows: 15 },
    loopRatio: 0.16,
    roomDivisor: 58,
    minimumRooms: 7,
    roomSize: { min: 2, max: 3 },
    seedSalt: 0x85ebca6b,
  },
  surfaces: {
    wall: {
      base: [102, 105, 91],
      accent: [73, 77, 68],
      grime: [39, 42, 36],
      pattern: 'painted-concrete',
      roughness: 0.88,
      metalness: 0.04,
      bumpScale: 0.064,
      grimeOpacity: 0.19,
    },
    floor: {
      base: [70, 71, 64],
      accent: [50, 51, 47],
      grime: [38, 35, 28],
      pattern: 'oil-stained-concrete',
      roughness: 0.9,
      metalness: 0.02,
      bumpScale: 0.052,
    },
    ceiling: {
      base: [76, 79, 72],
      accent: [53, 56, 51],
      grime: [35, 37, 33],
      pattern: 'service-slab',
      roughness: 0.87,
      metalness: 0.06,
      bumpScale: 0.048,
      emissive: 0x182016,
      emissiveIntensity: 0.18,
    },
    trim: { color: 0x42473f, roughness: 0.78, metalness: 0.18 },
  },
  fog: {
    color: 0x2d332e,
    density: { desktop: 0.037, mobile: 0.044 },
  },
  lighting: {
    exposure: 0.67,
    hemisphere: {
      sky: 0xa7b291,
      ground: 0x171a16,
      intensity: { desktop: 0.42, mobile: 0.49 },
    },
    ambient: {
      color: 0x5d6654,
      intensity: { desktop: 0.14, mobile: 0.2 },
    },
    fixture: {
      color: 0xd2ddba,
      panelColor: 0xd8e3c4,
      deadPanelColor: 0x343a32,
      intensity: 77,
      distance: 10.2,
      angle: 1.18,
      penumbra: 0.82,
      decay: 2,
      brokenChance: 0.24,
      pool: { desktop: 6, mobile: 3 },
      flicker: {
        idleRate: 5.8,
        idleDepth: 0.035,
        faultFloor: 0.018,
        recovery: 0.28,
      },
    },
  },
  audio: {
    drips: false,
    masterGain: 0.74,
    humGain: 0.057,
    oscillators: [
      { frequency: 50, type: 'sine', gain: 0.2 },
      { frequency: 100, type: 'sawtooth', gain: 0.035 },
      { frequency: 25, type: 'sine', gain: 0.13 },
      { frequency: 240, type: 'triangle', gain: 0.018 },
    ],
    noise: { filter: 'bandpass', frequency: 410, q: 0.72, gain: 0.032 },
    heartbeat: { startFrequency: 61, endFrequency: 34 },
    impact: { startFrequency: 46, endFrequency: 17 },
    footstep: { walkLowpass: 360, runLowpass: 470 },
    ambience: {
      interval: [8, 18],
      cues: ['pipe-knock', 'relay-chatter', 'steam-release', 'shift-bell'],
      stereoWidth: 0.86,
      silenceChance: 0.16,
    },
  },
  objective: {
    type: 'fuse',
    count: 3,
    color: 0xe0a43e,
    labels: {
      hud: 'RESTORE POWER',
      item: 'FUSE',
      itemPlural: 'FUSES',
      interact: 'E  REPLACE FUSE',
      progress: 'FUSES {current}/{total}',
      locked: 'FREIGHT LIFT HAS NO POWER',
      complete: 'POWER RESTORED / FIND THE LIFT',
    },
  },
  props: [
    { type: 'wall-pipe', density: 0.15, color: 0x555c55, accent: 0x252a26, cluster: [2, 5] },
    { type: 'wall-pipe', density: 0.035, color: 0x705f45, accent: 0x30251d, cluster: [1, 2] },
    { type: 'cable-tray', density: 0.056, color: 0x353a36, accent: 0x171a18, cluster: [2, 4] },
    { type: 'service-crate', density: 0.032, color: 0x695c3e, accent: 0x302b20, cluster: [1, 3] },
    { type: 'oil-drum', density: 0.022, color: 0x50594d, accent: 0xa36b28, cluster: [1, 2] },
  ],
  incidents: {
    density: 0.016,
    minCount: 3,
    maxCount: 8,
    minCellDistance: 3,
    weights: {
      'collapsed-wanderer': 0.9,
      'abandoned-pack': 1.6,
      'chair-pile': 1.15,
      'black-motes': 1.05,
      'shoe-trail': 0.9,
    },
  },
  atmosphere: {
    identity: 'failing-mechanical-undercroft',
    cadence: { first: [8, 14], interval: [12, 22] },
    pauseDuringChase: true,
    environmentalStory: [
      { id: 'shift-board', text: 'NIGHT SHIFT: 1 ASSIGNED / 0 CLOCKED IN', density: 0.008, placement: 'wall' },
      { id: 'lockout', text: 'LOCKOUT FAILED / DO NOT RESTORE', density: 0.007, placement: 'objective' },
      { id: 'lift-load', text: 'MAXIMUM LOAD: 1 PERSON / CURRENT LOAD: 2', density: 0.004, placement: 'exit' },
    ],
    milestones: [
      {
        id: 'warm-fuse',
        progress: 0.33,
        message: 'THE REPLACED FUSE WAS ALREADY WARM',
        duration: 1.2,
        cue: 'relay-chatter',
        effect: { flicker: 0.48 },
      },
      {
        id: 'lift-called',
        progress: 0.66,
        message: 'SOMEONE CALLED THE LIFT FROM BELOW',
        duration: 1.25,
        cue: 'shift-bell',
        effect: { flicker: 0.85 },
      },
    ],
    events: [
      {
        id: 'pipe-sequence',
        earliest: 9,
        weight: 1.2,
        maxRepeats: 3,
        tension: [0.04, 0.82],
        message: 'THE KNOCKING MOVES TO THE NEXT PIPE',
        duration: 1.05,
        cue: 'pipe-knock',
        pan: 'random',
      },
      {
        id: 'relay-answer',
        earliest: 18,
        weight: 0.9,
        maxRepeats: 2,
        tension: [0.12, 0.82],
        message: 'A RELAY ANSWERS FROM INSIDE THE WALL',
        duration: 1.1,
        cue: 'relay-chatter',
        effect: { flicker: 0.42, glitch: 0.34 },
      },
      {
        id: 'shift-bell',
        earliest: 26,
        weight: 0.58,
        maxRepeats: 1,
        tension: [0.18, 0.72],
        message: 'THE END-OF-SHIFT BELL RINGS ONCE',
        duration: 1.15,
        cue: 'shift-bell',
      },
      {
        id: 'pressure-follow',
        earliest: 32,
        weight: 0.86,
        maxRepeats: 2,
        tension: [0.22, 0.9],
        message: 'PIPE PRESSURE IS MOVING TOWARD YOU',
        duration: 1.2,
        cue: 'steam-release',
        pan: 'random',
      },
      {
        id: 'machine-stop',
        earliest: 45,
        weight: 0.5,
        maxRepeats: 1,
        tension: [0.3, 0.88],
        message: 'ALL MACHINERY STOPS AT ONCE',
        duration: 1.25,
        cue: 'machine-dropout',
        effect: { flicker: 1.4, silence: 1.35 },
      },
    ],
  },
  equipment: {
    flashlight: {
      color: 0xd8e8bd,
      intensity: 52,
      distance: 18,
      angle: 0.4,
      drainPerSecond: 0.0058,
      emergencyRechargePerSecond: 0.002,
      flashCost: 0.3,
    },
  },
  evidence: {
    recharge: 0.3,
    entries: [
      'WORK LOG 04 / THE FOREMAN CLOCKED IN TOMORROW',
      'WORK LOG 11 / DO NOT ANSWER KNOCKS IN THE PIPE',
      'WORK LOG 19 / THE LIFT ARRIVES WITH TWO SHADOWS',
    ],
  },
  monster: {
    name: 'The Foreman',
    identity: 'foreman',
    presentation: {
      silhouette: 'asymmetric-maintenance-husk',
      eyePulse: 0.34,
      twitchStrength: 0.92,
    },
    sound: {
      breathPitch: 0.72,
      breathWeight: 1.05,
      stepWeight: 1.28,
      drag: 0.18,
    },
    skin: {
      type: 'maintenance-husk',
      body: 0x151816,
      accent: 0x9c5b22,
      eye: 0xffd08a,
      emissiveIntensity: 1.8,
      scale: 1.12,
    },
    timing: {
      firstScare: [7, 12],
      scareInterval: [10, 21],
      firstChase: [30, 43],
      glimpseDuration: 1.05,
      stalkDuration: 18,
      pathRefresh: { stalk: 0.62, chase: 0.3 },
    },
    behavior: {
      sight: { range: 23, peripheralDot: 0.2, acquireRate: 1.52, threshold: 0.4 },
      hearing: { baseCells: 3, noiseCells: 11, chaseNoise: 0.68, reacquireNoise: 0.38 },
      chase: { lostSightDelay: 6.2, searchDuration: [8, 13], recovery: [14, 21] },
      wanderCells: [2, 6],
    },
    speeds: { watched: 0.44, stalk: 1.33, chase: 3.62 },
    stalkTriggerDistance: 11.4,
    catchDistance: 0.93,
  },
};
