// Auto-discovered campaign chapter; keep this module data-only and deterministic.
export default {
  id: 'school-halls',
  index: 9,
  name: 'School Halls',
  exit: { label: 'STAIRWELL C' },
  copy: {
    classification: 'THRESHOLD ARCHIVE / LEVEL 9',
    status: 'PERMANENT AFTER-SCHOOL SESSION',
    start: {
      kicker: 'EAST WING / FINAL BELL PASSED',
      title: 'CLASS IS<br />STILL IN SESSION.',
      body: 'Find Stairwell C. Do not enter a classroom when attendance is called.',
      button: 'ENTER LEVEL 9',
    },
    pause: {
      kicker: 'HALL PASS EXPIRED',
      title: 'FACE THE WALL<br />AND WAIT.',
      body: 'Chalk scratches behind doors with no rooms beyond them.',
      button: 'RETURN TO HALL',
    },
    death: {
      kicker: 'ABSENCE RECORDED',
      title: 'DESK<br />RESERVED.',
      body: 'Tomorrow has been canceled. The bell will ring anyway.',
      button: 'RETAKE ATTENDANCE',
    },
    win: {
      kicker: 'STAIRWELL C OPEN',
      title: 'THE LAST BELL<br />RINGS BELOW.',
      body: 'The stairwell empties into an office atrium with no visible sky.',
      button: 'DESCEND TO LEVEL 10',
    },
  },
  maze: {
    desktop: { cols: 25, rows: 25 },
    mobile: { cols: 19, rows: 19 },
    loopRatio: 0.22,
    roomDivisor: 47,
    minimumRooms: 11,
    roomSize: { min: 2, max: 4 },
    seedSalt: 0x9c4001a1,
  },
  surfaces: {
    wall: {
      base: [157, 166, 132],
      accent: [91, 111, 81],
      grime: [49, 56, 39],
      pattern: 'aged-wallpaper',
      roughness: 0.91,
      metalness: 0,
      bumpScale: 0.055,
      grimeOpacity: 0.22,
    },
    floor: {
      base: [93, 82, 63],
      accent: [59, 67, 53],
      grime: [33, 31, 24],
      pattern: 'damp-carpet',
      roughness: 0.86,
      metalness: 0,
      bumpScale: 0.042,
    },
    ceiling: {
      base: [178, 179, 156],
      accent: [127, 130, 108],
      grime: [72, 76, 58],
      pattern: 'acoustic-tile',
      roughness: 0.95,
      metalness: 0,
      bumpScale: 0.04,
      emissive: 0x323622,
      emissiveIntensity: 0.25,
    },
    trim: { color: 0x526545, roughness: 0.82, metalness: 0.04 },
  },
  fog: { color: 0x596049, density: { desktop: 0.034, mobile: 0.04 } },
  lighting: {
    exposure: 0.9,
    hemisphere: {
      sky: 0xdbe4b8,
      ground: 0x1c2117,
      intensity: { desktop: 0.58, mobile: 0.66 },
    },
    ambient: { color: 0x929c72, intensity: { desktop: 0.25, mobile: 0.32 } },
    fixture: {
      color: 0xf0fac2,
      panelColor: 0xf5ffd0,
      deadPanelColor: 0x454a39,
      intensity: 104,
      distance: 11.8,
      angle: 1.2,
      penumbra: 0.9,
      decay: 2,
      brokenChance: 0.2,
      pool: { desktop: 7, mobile: 4 },
      flicker: { idleRate: 5.1, idleDepth: 0.03, faultFloor: 0.02, recovery: 0.34 },
    },
  },
  audio: {
    drips: false,
    masterGain: 0.7,
    humGain: 0.05,
    oscillators: [
      { frequency: 60, type: 'sine', gain: 0.17 },
      { frequency: 180, type: 'triangle', gain: 0.018 },
      { frequency: 30, type: 'sine', gain: 0.1 },
    ],
    noise: { filter: 'bandpass', frequency: 540, q: 0.85, gain: 0.026 },
    heartbeat: { startFrequency: 68, endFrequency: 36 },
    impact: { startFrequency: 48, endFrequency: 17 },
    footstep: { walkLowpass: 245, runLowpass: 325 },
    ambience: {
      interval: [10, 23],
      cues: ['shift-bell', 'distant-ring', 'ballast-pop', 'distant-knock'],
      stereoWidth: 0.9,
      silenceChance: 0.24,
    },
  },
  objective: {
    type: 'none',
    count: 0,
    color: 0x91ad78,
    labels: {
      hud: 'FIND STAIRWELL C',
      item: '',
      itemPlural: '',
      interact: 'E  OPEN STAIRWELL',
      progress: '',
      locked: '',
      complete: 'STAIRWELL C LOCATED',
    },
  },
  props: [
    { type: 'discarded-chair', density: 0.041, color: 0x69563e, accent: 0xa88756, cluster: [2, 7] },
    { type: 'square-column', density: 0.017, color: 0x8e9875, accent: 0x4e6141, cluster: [1, 2] },
    { type: 'ceiling-vent', density: 0.05, color: 0x7b8170, accent: 0x383c32, cluster: [1, 4] },
    { type: 'school-locker', density: 0.014, color: 0x5c533f, accent: 0x968356, cluster: [1, 3] },
    { type: 'cable-tray', density: 0.026, color: 0x55584c, accent: 0x272923, cluster: [1, 4] },
  ],
  incidents: {
    density: 0.017,
    minCount: 4,
    maxCount: 9,
    minCellDistance: 3,
    weights: {
      'collapsed-wanderer': 0.55,
      'abandoned-pack': 1.25,
      'chair-pile': 2.2,
      'black-motes': 0.65,
      'shoe-trail': 1.8,
    },
    palette: { cloth: 0x4f5b43, clothLight: 0x89947a, motes: 0x11150d },
  },
  atmosphere: {
    identity: 'after-hours-school-wing',
    cadence: { first: [8, 14], interval: [13, 25] },
    pauseDuringChase: true,
    environmentalStory: [
      { id: 'class-list', text: 'ATTENDANCE: 0 PRESENT / 1 WALKING', density: 0.01, placement: 'wall' },
      { id: 'hall-arrow', text: 'STAIRWELL C → / ARROW CHANGES AFTER BELL', density: 0.008, placement: 'floor' },
      { id: 'late-slip', text: 'REASON FOR LATENESS: NOT BORN YET', density: 0.006, placement: 'exit' },
    ],
    milestones: [],
    events: [
      {
        id: 'single-bell', earliest: 6, weight: 1.3, maxRepeats: 3,
        tension: [0.02, 0.86], message: 'THE BELL RINGS ONCE. NO DOORS OPEN.', duration: 1.12,
        cue: 'shift-bell', pan: 'random',
      },
      {
        id: 'chalk-writing', earliest: 15, weight: 0.92, maxRepeats: 2,
        tension: [0.08, 0.84], message: 'CHALK WRITES YOUR FOOTSTEPS BEFORE YOU TAKE THEM', duration: 1.2,
        cue: 'distant-knock', effect: { glitch: 0.25 },
      },
      {
        id: 'locker-run', earliest: 27, weight: 0.66, maxRepeats: 2,
        tension: [0.16, 0.93], message: 'LOCKERS SLAM SHUT DOWN THE HALL TOWARD YOU', duration: 1.25,
        cue: 'relay-chatter', pan: 'random', effect: { flicker: 0.42 },
      },
      {
        id: 'attendance-call', earliest: 40, weight: 0.43, maxRepeats: 1,
        tension: [0.27, 0.9], message: 'A TEACHER CALLS YOUR NAME FROM EVERY ROOM', duration: 1.32,
        cue: 'distant-ring', effect: { silence: 1.45, flicker: 0.7 },
      },
    ],
  },
  equipment: {
    flashlight: {
      color: 0xf2f7c9,
      intensity: 53,
      distance: 18,
      angle: 0.4,
      drainPerSecond: 0.0052,
      emergencyRechargePerSecond: 0.0021,
      flashCost: 0.28,
    },
  },
  evidence: {
    recharge: 0.31,
    entries: [
      'HALL PASS 09 / DESTINATION: STAIRWELL C / RETURN: NEVER',
      'GRADE BOOK / FINAL MARKS RECORDED FOR STUDENTS NOT YET BORN',
      'CUSTODIAN NOTE / DO NOT ERASE THE FIGURE DRAWN BEHIND YOU',
    ],
  },
  monster: {
    name: 'The Hall Monitor',
    identity: 'still',
    presentation: { silhouette: 'wire-rib-sentinel', eyePulse: 0, twitchStrength: 0.95 },
    sound: { breathPitch: 0.73, breathWeight: 0.44, stepWeight: 0.7, drag: 0.2 },
    skin: {
      type: 'faceless-shadow',
      body: 0x050704,
      accent: 0x27301e,
      eye: null,
      emissiveIntensity: 0,
      scale: 1.02,
    },
    timing: {
      firstScare: [10, 17],
      scareInterval: [13, 25],
      firstChase: [45, 62],
      glimpseDuration: 1.28,
      stalkDuration: 24,
      pathRefresh: { stalk: 0.72, chase: 0.32 },
    },
    behavior: {
      sight: { range: 23, peripheralDot: 0.25, acquireRate: 1.02, threshold: 0.54 },
      hearing: { baseCells: 3, noiseCells: 10, chaseNoise: 0.75, reacquireNoise: 0.43 },
      chase: { lostSightDelay: 5.1, searchDuration: [8, 13], recovery: [18, 27] },
      wanderCells: [4, 8],
    },
    speeds: { watched: 0.15, stalk: 1.25, chase: 3.58 },
    stalkTriggerDistance: 11.8,
    catchDistance: 0.89,
  },
};
