// Auto-discovered campaign chapter; keep this module data-only and deterministic.
export default {
  id: 'subway-service',
  index: 11,
  name: 'Subway Service',
  exit: { label: 'TRACK ACCESS' },
  copy: {
    classification: 'THRESHOLD ARCHIVE / LEVEL 11',
    status: 'SERVICE LINE ENERGIZED',
    start: {
      kicker: 'TRANSIT SERVICE / PLATFORM OMITTED',
      title: 'THE TRAIN<br />DOES NOT STOP.',
      body: 'Close four pressure valves. Keep off the rails when the tunnel wind arrives.',
      button: 'ENTER LEVEL 11',
    },
    pause: {
      kicker: 'SIGNAL HELD AT RED',
      title: 'STAND BEHIND<br />THE YELLOW LINE.',
      body: 'Something is walking the track bed against the current.',
      button: 'CLEAR SIGNAL',
    },
    death: {
      kicker: 'PASSENGER SERVICE TERMINATED',
      title: 'LAST STOP<br />MISSED.',
      body: 'The arrival board adds your name beneath DELAYED INDEFINITELY.',
      button: 'REENTER SERVICE',
    },
    win: {
      kicker: 'TRACK ACCESS UNSEALED',
      title: 'THE TUNNEL<br />DESCENDS.',
      body: 'The rails vanish under heat, steam, and the rhythm of industrial drums.',
      button: 'DESCEND TO LEVEL 12',
    },
  },
  maze: {
    desktop: { cols: 33, rows: 17 },
    mobile: { cols: 25, rows: 15 },
    loopRatio: 0.29,
    roomDivisor: 70,
    minimumRooms: 6,
    roomSize: { min: 2, max: 5 },
    seedSalt: 0xb57a1109,
  },
  surfaces: {
    wall: {
      base: [91, 106, 99],
      accent: [55, 75, 68],
      grime: [24, 35, 31],
      pattern: 'seeping-concrete',
      roughness: 0.88,
      metalness: 0.04,
      bumpScale: 0.08,
      grimeOpacity: 0.27,
    },
    floor: {
      base: [63, 72, 68],
      accent: [116, 91, 51],
      grime: [20, 27, 25],
      pattern: 'flooded-concrete',
      roughness: 0.48,
      metalness: 0.08,
      bumpScale: 0.032,
    },
    ceiling: {
      base: [74, 86, 80],
      accent: [48, 61, 55],
      grime: [22, 31, 28],
      pattern: 'dripping-concrete',
      roughness: 0.92,
      metalness: 0.03,
      bumpScale: 0.075,
      emissive: 0x15281f,
      emissiveIntensity: 0.17,
    },
    trim: { color: 0x465d54, roughness: 0.67, metalness: 0.27 },
  },
  fog: { color: 0x1d342c, density: { desktop: 0.046, mobile: 0.053 } },
  lighting: {
    exposure: 0.76,
    hemisphere: {
      sky: 0x91b9a7,
      ground: 0x0c1512,
      intensity: { desktop: 0.4, mobile: 0.48 },
    },
    ambient: { color: 0x4f7867, intensity: { desktop: 0.17, mobile: 0.24 } },
    fixture: {
      color: 0xffc36f,
      panelColor: 0xffd18b,
      deadPanelColor: 0x34423c,
      intensity: 91,
      distance: 13,
      angle: 1.12,
      penumbra: 0.84,
      decay: 2,
      brokenChance: 0.29,
      pool: { desktop: 7, mobile: 4 },
      flicker: { idleRate: 2.5, idleDepth: 0.055, faultFloor: 0.01, recovery: 0.5 },
    },
  },
  audio: {
    drips: true,
    masterGain: 0.82,
    humGain: 0.07,
    oscillators: [
      { frequency: 36, type: 'sine', gain: 0.3 },
      { frequency: 72, type: 'triangle', gain: 0.055 },
      { frequency: 18, type: 'sine', gain: 0.18 },
      { frequency: 144, type: 'sawtooth', gain: 0.009 },
    ],
    noise: { filter: 'lowpass', frequency: 260, q: 0.8, gain: 0.052 },
    heartbeat: { startFrequency: 58, endFrequency: 29 },
    impact: { startFrequency: 34, endFrequency: 11 },
    footstep: { walkLowpass: 170, runLowpass: 235 },
    ambience: {
      interval: [7, 18],
      cues: ['pressure-groan', 'chain-drag', 'far-splash', 'relay-chatter'],
      stereoWidth: 1,
      silenceChance: 0.12,
    },
  },
  objective: {
    type: 'valve',
    count: 4,
    color: 0xd6a353,
    labels: {
      hud: 'ISOLATE THE SERVICE MAIN',
      item: 'PRESSURE VALVE',
      itemPlural: 'PRESSURE VALVES',
      interact: 'E  CLOSE VALVE',
      progress: 'MAINS ISOLATED {current}/{total}',
      locked: 'TRACK ACCESS UNDER PRESSURE',
      complete: 'SERVICE MAIN ISOLATED / FIND TRACK ACCESS',
    },
  },
  props: [
    { type: 'wall-pipe', density: 0.115, color: 0x4f665c, accent: 0x1e2b26, cluster: [3, 7] },
    { type: 'cable-tray', density: 0.078, color: 0x46544f, accent: 0x1c2421, cluster: [2, 6] },
    { type: 'drain-grate', density: 0.045, color: 0x283732, accent: 0x101714, cluster: [1, 3] },
    { type: 'standing-water', density: 0.09, color: 0x31564a, accent: 0x8da99e, cluster: [2, 7] },
    { type: 'hanging-chain', density: 0.03, color: 0x52635c, accent: 0x202925, cluster: [1, 4] },
  ],
  incidents: {
    density: 0.019,
    minCount: 4,
    maxCount: 10,
    minCellDistance: 4,
    weights: {
      'collapsed-wanderer': 1.15,
      'abandoned-pack': 0.85,
      'chair-pile': 0.25,
      'black-motes': 1.8,
      'shoe-trail': 1.55,
    },
    palette: { cloth: 0x30463e, clothLight: 0x637d72, motes: 0x030806 },
  },
  atmosphere: {
    identity: 'unmapped-subway-service-line',
    cadence: { first: [6, 12], interval: [11, 21] },
    pauseDuringChase: true,
    environmentalStory: [
      { id: 'signal-board', text: 'SIGNAL CLEAR / TRACK OCCUPIED BY FOOTSTEPS', density: 0.009, placement: 'wall' },
      { id: 'rail-warning', text: 'THIRD RAIL LIVE / FIRST AND SECOND BREATHING', density: 0.008, placement: 'floor' },
      { id: 'valve-plate', text: 'SERVICE MAIN / DESTINATION NOT ON MAP', density: 0.006, placement: 'objective' },
    ],
    milestones: [
      {
        id: 'subway-half-pressure',
        progress: 0.5,
        message: 'TUNNEL WIND ARRIVES WITHOUT A TRAIN',
        duration: 1.22,
        cue: 'pressure-groan',
        effect: { flicker: 0.5 },
      },
      {
        id: 'subway-main-closed',
        progress: 1,
        message: 'THE ARRIVAL BOARD CHANGES TO WALKING',
        duration: 1.3,
        cue: 'relay-chatter',
        effect: { glitch: 0.34, silence: 1.1 },
      },
    ],
    events: [
      {
        id: 'rail-hum', earliest: 4, weight: 1.3, maxRepeats: 3,
        tension: [0.02, 0.88], message: 'THE THIRD RAIL HUMS BENEATH YOUR FOOTSTEP', duration: 1.08,
        cue: 'relay-chatter', pan: 'random',
      },
      {
        id: 'tunnel-train', earliest: 13, weight: 1, maxRepeats: 3,
        tension: [0.08, 0.86], message: 'A TRAIN PASSES BEHIND THE CONCRETE WALL', duration: 1.2,
        cue: 'pressure-groan', pan: 'random',
      },
      {
        id: 'track-step', earliest: 24, weight: 0.72, maxRepeats: 2,
        tension: [0.15, 0.94], message: 'WET FOOTSTEPS KEEP PACE ON THE TRACK BED', duration: 1.24,
        cue: 'far-splash', pan: 'random',
      },
      {
        id: 'signal-dark', earliest: 37, weight: 0.47, maxRepeats: 1,
        tension: [0.25, 0.92], message: 'EVERY SIGNAL GOES DARK EXCEPT THE ONE BEHIND YOU', duration: 1.32,
        cue: 'machine-dropout', effect: { flicker: 1.25, silence: 1.55 },
      },
    ],
  },
  equipment: {
    flashlight: {
      color: 0xffd19a,
      intensity: 63,
      distance: 22.5,
      angle: 0.35,
      drainPerSecond: 0.0065,
      emergencyRechargePerSecond: 0.0017,
      flashCost: 0.34,
    },
  },
  evidence: {
    recharge: 0.26,
    entries: [
      'SIGNAL LOG 11 / TRAIN DETECTED MOVING BETWEEN PARALLEL WALLS',
      'TRANSIT MAP / THIS SERVICE CORRIDOR CROSSES EVERY STATION ONCE',
      'TRACK REPORT / WET PRINTS CONTINUE THROUGH THE LIVE RAIL',
    ],
  },
  monster: {
    name: 'The Trackwalker',
    identity: 'wader',
    presentation: { silhouette: 'waterlogged-dragger', eyePulse: 0.7, twitchStrength: 0.62 },
    sound: { breathPitch: 0.48, breathWeight: 1.1, stepWeight: 1.04, drag: 0.72 },
    skin: {
      type: 'waterlogged-longlimb',
      body: 0x06100c,
      accent: 0x315d4e,
      eye: 0xe4b35f,
      emissiveIntensity: 0.66,
      scale: 1.22,
    },
    timing: {
      firstScare: [8, 15],
      scareInterval: [11, 21],
      firstChase: [36, 52],
      glimpseDuration: 1.04,
      stalkDuration: 19,
      pathRefresh: { stalk: 0.48, chase: 0.23 },
    },
    behavior: {
      sight: { range: 18, peripheralDot: 0.12, acquireRate: 1.62, threshold: 0.39 },
      hearing: { baseCells: 5, noiseCells: 15, chaseNoise: 0.54, reacquireNoise: 0.29 },
      chase: { lostSightDelay: 6.8, searchDuration: [11, 18], recovery: [13, 20] },
      wanderCells: [4, 10],
    },
    speeds: { watched: 0.58, stalk: 1.48, chase: 3.92 },
    stalkTriggerDistance: 12.2,
    catchDistance: 0.99,
  },
};
