// Auto-discovered campaign chapter; keep this module data-only and deterministic.
export default {
  id: 'industrial-laundry',
  index: 12,
  name: 'Industrial Laundry',
  exit: { label: 'SOILED EXIT' },
  copy: {
    classification: 'THRESHOLD ARCHIVE / LEVEL 12',
    status: 'WASH CYCLE WILL NOT END',
    start: {
      kicker: 'CENTRAL LAUNDRY / SHIFT 00',
      title: 'THE MACHINES<br />ARE FULL OF AIR.',
      body: 'Close five steam valves. The empty drums turn at the rhythm of your pulse.',
      button: 'ENTER LEVEL 12',
    },
    pause: {
      kicker: 'CYCLE TEMPORARILY HELD',
      title: 'DO NOT OPEN<br />THE DRUMS.',
      body: 'Wet cloth drags across the floor where nothing is visible.',
      button: 'RESUME CYCLE',
    },
    death: {
      kicker: 'LOAD WEIGHT ACCEPTED',
      title: 'CYCLE<br />COMPLETE.',
      body: 'The press folds one more human-shaped sheet.',
      button: 'RESTART WASH',
    },
    win: {
      kicker: 'SOILED EXIT RELEASED',
      title: 'THE STEAM<br />CLEARS BELOW.',
      body: 'Beyond the service door, checkout lanes wait under clean white light.',
      button: 'DESCEND TO LEVEL 13',
    },
  },
  maze: {
    desktop: { cols: 23, rows: 29 },
    mobile: { cols: 17, rows: 23 },
    loopRatio: 0.24,
    roomDivisor: 49,
    minimumRooms: 10,
    roomSize: { min: 2, max: 5 },
    seedSalt: 0xc1ea4d12,
  },
  surfaces: {
    wall: {
      base: [139, 154, 151],
      accent: [79, 103, 99],
      grime: [38, 55, 51],
      pattern: 'painted-concrete',
      roughness: 0.82,
      metalness: 0.03,
      bumpScale: 0.055,
      grimeOpacity: 0.19,
    },
    floor: {
      base: [91, 107, 105],
      accent: [55, 74, 71],
      grime: [28, 42, 39],
      pattern: 'flooded-concrete',
      roughness: 0.43,
      metalness: 0.07,
      bumpScale: 0.026,
    },
    ceiling: {
      base: [117, 132, 128],
      accent: [77, 94, 90],
      grime: [39, 55, 51],
      pattern: 'dripping-concrete',
      roughness: 0.9,
      metalness: 0.03,
      bumpScale: 0.06,
      emissive: 0x253b38,
      emissiveIntensity: 0.23,
    },
    trim: { color: 0x58716c, roughness: 0.6, metalness: 0.33 },
  },
  fog: { color: 0x617873, density: { desktop: 0.042, mobile: 0.049 } },
  lighting: {
    exposure: 0.85,
    hemisphere: {
      sky: 0xc8e0dc,
      ground: 0x14201e,
      intensity: { desktop: 0.51, mobile: 0.59 },
    },
    ambient: { color: 0x7fa49d, intensity: { desktop: 0.22, mobile: 0.29 } },
    fixture: {
      color: 0xe3fff8,
      panelColor: 0xeefffb,
      deadPanelColor: 0x3c504c,
      intensity: 99,
      distance: 12,
      angle: 1.18,
      penumbra: 0.88,
      decay: 2,
      brokenChance: 0.24,
      pool: { desktop: 7, mobile: 4 },
      flicker: { idleRate: 3.3, idleDepth: 0.04, faultFloor: 0.016, recovery: 0.4 },
    },
  },
  audio: {
    drips: true,
    masterGain: 0.84,
    humGain: 0.075,
    oscillators: [
      { frequency: 44, type: 'sine', gain: 0.28 },
      { frequency: 88, type: 'triangle', gain: 0.06 },
      { frequency: 22, type: 'sine', gain: 0.16 },
      { frequency: 176, type: 'square', gain: 0.006 },
    ],
    noise: { filter: 'bandpass', frequency: 430, q: 0.72, gain: 0.05 },
    heartbeat: { startFrequency: 60, endFrequency: 31 },
    impact: { startFrequency: 39, endFrequency: 13 },
    footstep: { walkLowpass: 185, runLowpass: 255 },
    ambience: {
      interval: [7, 17],
      cues: ['steam-release', 'machine-dropout', 'chain-drag', 'shift-bell'],
      stereoWidth: 0.96,
      silenceChance: 0.13,
    },
  },
  objective: {
    type: 'valve',
    count: 5,
    color: 0x8fd2c4,
    labels: {
      hud: 'SHUT DOWN THE STEAM HEADER',
      item: 'STEAM VALVE',
      itemPlural: 'STEAM VALVES',
      interact: 'E  CLOSE STEAM VALVE',
      progress: 'VALVES CLOSED {current}/{total}',
      locked: 'SOILED EXIT HEAT-LOCKED',
      complete: 'STEAM HEADER COLD / FIND SOILED EXIT',
    },
  },
  props: [
    { type: 'wall-pipe', density: 0.12, color: 0x617a75, accent: 0x273a36, cluster: [3, 8] },
    { type: 'hanging-chain', density: 0.044, color: 0x5a6f6a, accent: 0x222d2a, cluster: [1, 5] },
    { type: 'standing-water', density: 0.082, color: 0x41665e, accent: 0xb2d8cf, cluster: [2, 7] },
    { type: 'service-crate', density: 0.019, color: 0x4f5e5a, accent: 0x829b95, cluster: [1, 3] },
    { type: 'oil-drum', density: 0.015, color: 0x526661, accent: 0x87a69e, cluster: [1, 2] },
    { type: 'ceiling-vent', density: 0.047, color: 0x758985, accent: 0x334440, cluster: [1, 4] },
  ],
  incidents: {
    density: 0.02,
    minCount: 4,
    maxCount: 10,
    minCellDistance: 3,
    weights: {
      'collapsed-wanderer': 1.2,
      'abandoned-pack': 1.7,
      'chair-pile': 0.35,
      'black-motes': 1.5,
      'shoe-trail': 1.4,
    },
    palette: { cloth: 0x788d87, clothLight: 0xc4d4d0, motes: 0x07100e },
  },
  atmosphere: {
    identity: 'industrial-laundry-night-cycle',
    cadence: { first: [6, 12], interval: [10, 20] },
    pauseDuringChase: true,
    environmentalStory: [
      { id: 'wash-chart', text: 'LOAD TYPE: AIR / WEIGHT: INCREASING', density: 0.009, placement: 'wall' },
      { id: 'wet-drag', text: 'WET MARK ENDS / DRAGGING SOUND CONTINUES', density: 0.008, placement: 'floor' },
      { id: 'steam-tag', text: 'HEADER PRESSURE MATCHES HEART RATE', density: 0.006, placement: 'objective' },
    ],
    milestones: [
      {
        id: 'laundry-two-valves',
        progress: 0.4,
        message: 'THE DRUMS SLOW TO THE RHYTHM OF BREATHING',
        duration: 1.2,
        cue: 'machine-dropout',
        effect: { flicker: 0.4 },
      },
      {
        id: 'laundry-header-cold',
        progress: 1,
        message: 'EVERY MACHINE DOOR UNLATCHES AT ONCE',
        duration: 1.3,
        cue: 'steam-release',
        effect: { silence: 1.35, glitch: 0.3 },
      },
    ],
    events: [
      {
        id: 'empty-spin', earliest: 4, weight: 1.35, maxRepeats: 3,
        tension: [0.02, 0.88], message: 'AN EMPTY DRUM BEGINS ITS SPIN CYCLE', duration: 1.08,
        cue: 'machine-dropout', pan: 'random',
      },
      {
        id: 'steam-shape', earliest: 12, weight: 1, maxRepeats: 3,
        tension: [0.08, 0.88], message: 'STEAM HOLDS A HUMAN SHAPE AFTER THE VENT CLOSES', duration: 1.2,
        cue: 'steam-release', effect: { glitch: 0.24 },
      },
      {
        id: 'cart-roll', earliest: 23, weight: 0.72, maxRepeats: 2,
        tension: [0.15, 0.94], message: 'A LINEN CART ROLLS PAST THE NEXT CORRIDOR', duration: 1.22,
        cue: 'chain-drag', pan: 'random',
      },
      {
        id: 'cycle-end', earliest: 35, weight: 0.48, maxRepeats: 1,
        tension: [0.25, 0.92], message: 'THE END-OF-CYCLE BELL RINGS INSIDE YOUR CHEST', duration: 1.32,
        cue: 'shift-bell', effect: { flicker: 1.1, silence: 1.5 },
      },
    ],
  },
  equipment: {
    flashlight: {
      color: 0xd9fff6,
      intensity: 59,
      distance: 19.5,
      angle: 0.36,
      drainPerSecond: 0.006,
      emergencyRechargePerSecond: 0.0018,
      flashCost: 0.32,
    },
  },
  evidence: {
    recharge: 0.27,
    entries: [
      'SHIFT CARD 12 / OPERATOR CLOCKED OUT WHILE STILL ON CAMERA',
      'WASH FORMULA / ONE PART WATER / ONE PART REMEMBERED VOICE',
      'PRESS LOG / SHEETS ARRIVE FOLDED AROUND AN ABSENT BODY',
    ],
  },
  monster: {
    name: 'The Presser',
    identity: 'foreman',
    presentation: { silhouette: 'asymmetric-maintenance-husk', eyePulse: 0.58, twitchStrength: 1.05 },
    sound: { breathPitch: 0.52, breathWeight: 0.92, stepWeight: 0.9, drag: 0.58 },
    skin: {
      type: 'maintenance-husk',
      body: 0x07100e,
      accent: 0x3e7368,
      eye: 0xa8fff0,
      emissiveIntensity: 0.54,
      scale: 1.18,
    },
    timing: {
      firstScare: [8, 14],
      scareInterval: [10, 20],
      firstChase: [35, 50],
      glimpseDuration: 1.02,
      stalkDuration: 18,
      pathRefresh: { stalk: 0.46, chase: 0.22 },
    },
    behavior: {
      sight: { range: 20, peripheralDot: 0.18, acquireRate: 1.5, threshold: 0.42 },
      hearing: { baseCells: 4.6, noiseCells: 14, chaseNoise: 0.57, reacquireNoise: 0.31 },
      chase: { lostSightDelay: 6, searchDuration: [10, 16], recovery: [12, 19] },
      wanderCells: [3, 8],
    },
    speeds: { watched: 0.55, stalk: 1.52, chase: 4 },
    stalkTriggerDistance: 11.5,
    catchDistance: 0.97,
  },
};
