// Auto-discovered campaign chapter; keep this module data-only and deterministic.
export default {
  id: 'level-0',
  index: 0,
  name: 'The Lobby',
  exit: { label: 'EXIT' },
  copy: {
    classification: 'THRESHOLD ARCHIVE / LEVEL 0',
    status: 'SIGNAL LOST',
    start: {
      kicker: 'UNVERIFIED FOOTAGE',
      title: 'YOU WERE<br />NEVER HERE.',
      body: 'The carpet is damp. The hum does not come from the lights. It comes from the rooms.',
      button: 'ENTER LEVEL 0',
    },
    pause: {
      kicker: 'CONNECTION INTERRUPTED',
      title: 'DON\'T STAND<br />STILL.',
      body: 'Something keeps moving when the picture stops.',
      button: 'KEEP MOVING',
    },
    death: {
      kicker: 'SUBJECT NOT RECOVERED',
      title: 'IT FOUND<br />YOU.',
      body: 'The footage continues for another eleven minutes.',
      button: 'WAKE UP AGAIN',
    },
    win: {
      kicker: 'THRESHOLD CROSSED',
      title: 'THE STAIRS<br />GO DOWN.',
      body: 'The EXIT sign led to a service stair that is not on the building plan.',
      button: 'DESCEND TO LEVEL 1',
    },
  },
  maze: {
    desktop: { cols: 23, rows: 23 },
    mobile: { cols: 17, rows: 17 },
    loopRatio: 0.34,
    roomDivisor: 54,
    minimumRooms: 8,
    roomSize: { min: 2, max: 3 },
    seedSalt: 0x9e3779b9,
  },
  surfaces: {
    wall: {
      base: [183, 174, 91],
      accent: [156, 145, 68],
      grime: [59, 54, 25],
      pattern: 'aged-wallpaper',
      roughness: 0.93,
      metalness: 0,
      bumpScale: 0.045,
      grimeOpacity: 0.19,
    },
    floor: {
      base: [92, 83, 48],
      accent: [67, 59, 34],
      grime: [46, 44, 24],
      pattern: 'damp-carpet',
      roughness: 1,
      metalness: 0,
      bumpScale: 0.072,
    },
    ceiling: {
      base: [178, 176, 148],
      accent: [146, 143, 118],
      grime: [92, 89, 67],
      pattern: 'acoustic-tile',
      roughness: 0.92,
      metalness: 0,
      bumpScale: 0.035,
      emissive: 0x312f1d,
      emissiveIntensity: 0.32,
    },
    trim: { color: 0x746b42, roughness: 0.92, metalness: 0 },
  },
  fog: {
    color: 0x6c6849,
    density: { desktop: 0.028, mobile: 0.035 },
  },
  lighting: {
    exposure: 0.84,
    hemisphere: {
      sky: 0xd8cb83,
      ground: 0x282613,
      intensity: { desktop: 0.6, mobile: 0.66 },
    },
    ambient: {
      color: 0x8e8550,
      intensity: { desktop: 0.23, mobile: 0.29 },
    },
    fixture: {
      color: 0xffefad,
      panelColor: 0xfff0b0,
      deadPanelColor: 0x4a4935,
      intensity: 102,
      distance: 11.2,
      angle: 1.26,
      penumbra: 0.94,
      decay: 2,
      brokenChance: 0.07,
      pool: { desktop: 5, mobile: 3 },
      flicker: {
        idleRate: 3.2,
        idleDepth: 0.035,
        faultFloor: 0.018,
        recovery: 0.14,
      },
    },
  },
  audio: {
    drips: false,
    masterGain: 0.74,
    humGain: 0.088,
    oscillators: [
      { frequency: 60, type: 'sine', gain: 0.28 },
      { frequency: 120, type: 'triangle', gain: 0.08 },
      { frequency: 180, type: 'sine', gain: 0.02 },
      { frequency: 31, type: 'sine', gain: 0.12 },
    ],
    noise: { filter: 'bandpass', frequency: 540, q: 0.48, gain: 0.038 },
    heartbeat: { startFrequency: 64, endFrequency: 36 },
    impact: { startFrequency: 51, endFrequency: 19 },
    footstep: { walkLowpass: 220, runLowpass: 290 },
    ambience: {
      interval: [16, 34],
      cues: ['ballast-pop', 'distant-knock', 'fluorescent-dropout'],
      stereoWidth: 0.82,
      silenceChance: 0.48,
    },
  },
  objective: {
    type: 'none',
    count: 0,
    color: 0x86a77d,
    labels: {
      hud: 'KEEP MOVING',
      item: '',
      itemPlural: '',
      interact: 'E  OPEN',
      progress: '',
      locked: '',
      complete: 'AN EXIT EXISTS',
    },
  },
  props: [
    { type: 'square-column', density: 0.028, color: 0xaaa05e, accent: 0x70683d, cluster: [1, 2] },
    { type: 'ceiling-vent', density: 0.02, color: 0x686858, accent: 0x272820, cluster: [1, 2] },
    { type: 'discarded-chair', density: 0.01, color: 0x4f4b34, accent: 0x25251e, cluster: [1, 1] },
    { type: 'discarded-chair', density: 0.004, color: 0x66593d, accent: 0x2b2921, cluster: [2, 3] },
  ],
  incidents: {
    density: 0.009,
    minCount: 1,
    maxCount: 4,
    minCellDistance: 4,
    weights: {
      'collapsed-wanderer': 0.4,
      'abandoned-pack': 1.25,
      'chair-pile': 1.8,
      'black-motes': 0.55,
      'shoe-trail': 1.3,
    },
  },
  atmosphere: {
    identity: 'overlit-uncanny-office',
    cadence: { first: [18, 32], interval: [24, 44] },
    pauseDuringChase: true,
    environmentalStory: [
      { id: 'capacity', text: 'MEETING ROOM 4 / CAPACITY 0', density: 0.005, placement: 'wall' },
      { id: 'evacuation', text: 'EVACUATION ROUTE: RETURN TO DESK', density: 0.004, placement: 'wall' },
      { id: 'ceiling-log', text: 'TILE 07 REPLACED / TILE 07 REPLACED', density: 0.003, placement: 'fixture' },
    ],
    milestones: [],
    events: [
      {
        id: 'ballast-behind',
        earliest: 22,
        weight: 1.1,
        maxRepeats: 2,
        tension: [0.06, 0.7],
        message: 'THE HUM DROPS OUT BEHIND YOU',
        duration: 1.55,
        cue: 'ballast-pop',
        effect: { flicker: 0.9, silence: 1.6 },
      },
      {
        id: 'warm-carpet',
        earliest: 36,
        weight: 0.85,
        maxRepeats: 1,
        tension: [0.1, 0.65],
        message: 'THE CARPET GIVES UNDER YOUR WEIGHT',
        duration: 1.45,
        cue: 'sub-bass-bump',
      },
      {
        id: 'wrong-corridor',
        earliest: 48,
        weight: 0.95,
        maxRepeats: 2,
        tension: [0.14, 0.78],
        message: 'YOU HAVE WALKED THIS STRETCH BEFORE',
        duration: 1.55,
        cue: 'distant-knock',
        effect: { glitch: 0.22 },
      },
      {
        id: 'telephone',
        earliest: 62,
        weight: 0.5,
        maxRepeats: 1,
        tension: [0.16, 0.68],
        message: 'A PHONE RINGS WITH NO ROOM TO ANSWER',
        duration: 1.5,
        cue: 'distant-ring',
        pan: 'random',
      },
      {
        id: 'ventilation-stop',
        earliest: 78,
        weight: 0.7,
        maxRepeats: 1,
        tension: [0.22, 0.85],
        message: 'THE AIR STOPS MOVING',
        duration: 1.7,
        cue: 'fluorescent-dropout',
        effect: { flicker: 0.45, silence: 2.8 },
      },
    ],
  },
  equipment: {
    flashlight: {
      color: 0xffe7a0,
      intensity: 48,
      distance: 17,
      angle: 0.44,
      drainPerSecond: 0.0052,
      emergencyRechargePerSecond: 0.0022,
      flashCost: 0.28,
    },
  },
  evidence: {
    recharge: 0.34,
    entries: [
      'ARCHIVE 01 / THIS OFFICE HAS NO STREET ADDRESS',
      'ARCHIVE 02 / THE HUM CHANGES WHEN YOU BLINK',
      'ARCHIVE 03 / EVERY EXIT GOES ONE FLOOR LOWER',
    ],
  },
  monster: {
    name: 'The Still',
    identity: 'still',
    presentation: {
      silhouette: 'wire-rib-sentinel',
      eyePulse: 0,
      twitchStrength: 1.25,
    },
    sound: {
      breathPitch: 0.54,
      breathWeight: 0.44,
      stepWeight: 0.62,
      drag: 0.24,
    },
    skin: {
      type: 'faceless-shadow',
      body: 0x050604,
      accent: 0x11130f,
      eye: null,
      emissiveIntensity: 0,
      scale: 1.08,
    },
    timing: {
      firstScare: [22, 38],
      scareInterval: [22, 42],
      firstChase: [70, 95],
      glimpseDuration: 1.55,
      stalkDuration: 28,
      pathRefresh: { stalk: 0.95, chase: 0.42 },
    },
    behavior: {
      sight: { range: 22, peripheralDot: 0.38, acquireRate: 0.92, threshold: 0.58 },
      hearing: { baseCells: 2, noiseCells: 6, chaseNoise: 0.88, reacquireNoise: 0.55 },
      chase: { lostSightDelay: 3.8, searchDuration: [9, 14], recovery: [26, 38] },
      wanderCells: [4, 9],
    },
    speeds: { watched: 0.12, stalk: 0.92, chase: 3.05 },
    stalkTriggerDistance: 9.4,
    catchDistance: 0.88,
  },
};
