// Auto-discovered campaign chapter; keep this module data-only and deterministic.
export default {
  id: 'level-0',
  index: 0,
  name: 'The Lobby',
  exit: { label: 'EXIT' },
  copy: {
    classification: 'THRESHOLD ARCHIVE / LEVEL 0',
    status: 'SIGNAL LOST',
    start: {
      kicker: 'UNVERIFIED FOOTAGE',
      title: 'YOU WERE<br />NEVER HERE.',
      body: 'The carpet is damp. Every room is occupied by the same fluorescent hum.',
      button: 'ENTER LEVEL 0',
    },
    pause: {
      kicker: 'CONNECTION INTERRUPTED',
      title: 'DON\'T STAND<br />STILL.',
      body: 'Something keeps moving when the picture stops.',
      button: 'KEEP MOVING',
    },
    death: {
      kicker: 'SUBJECT NOT RECOVERED',
      title: 'IT FOUND<br />YOU.',
      body: 'The footage continues for another eleven minutes.',
      button: 'WAKE UP AGAIN',
    },
    win: {
      kicker: 'THRESHOLD CROSSED',
      title: 'THE STAIRS<br />GO DOWN.',
      body: 'The EXIT sign led to a service stair that is not on the building plan.',
      button: 'DESCEND TO LEVEL 1',
    },
  },
  maze: {
    desktop: { cols: 21, rows: 21 },
    mobile: { cols: 17, rows: 17 },
    loopRatio: 0.26,
    roomDivisor: 42,
    minimumRooms: 10,
    roomSize: { min: 2, max: 4 },
    seedSalt: 0x9e3779b9,
  },
  surfaces: {
    wall: {
      base: [183, 174, 91],
      accent: [156, 145, 68],
      grime: [59, 54, 25],
      pattern: 'aged-wallpaper',
      roughness: 0.93,
      metalness: 0,
      bumpScale: 0.045,
      grimeOpacity: 0.19,
    },
    floor: {
      base: [92, 83, 48],
      accent: [67, 59, 34],
      grime: [46, 44, 24],
      pattern: 'damp-carpet',
      roughness: 1,
      metalness: 0,
      bumpScale: 0.072,
    },
    ceiling: {
      base: [178, 176, 148],
      accent: [146, 143, 118],
      grime: [92, 89, 67],
      pattern: 'acoustic-tile',
      roughness: 0.92,
      metalness: 0,
      bumpScale: 0.035,
      emissive: 0x312f1d,
      emissiveIntensity: 0.32,
    },
    trim: { color: 0x746b42, roughness: 0.92, metalness: 0 },
  },
  fog: {
    color: 0x6c6849,
    density: { desktop: 0.026, mobile: 0.032 },
  },
  lighting: {
    exposure: 0.87,
    hemisphere: {
      sky: 0xd8cb83,
      ground: 0x282613,
      intensity: { desktop: 0.62, mobile: 0.68 },
    },
    ambient: {
      color: 0x8e8550,
      intensity: { desktop: 0.24, mobile: 0.3 },
    },
    fixture: {
      color: 0xffefad,
      panelColor: 0xfff0b0,
      deadPanelColor: 0x4a4935,
      intensity: 104,
      distance: 11.5,
      angle: 1.26,
      penumbra: 0.92,
      decay: 2,
      brokenChance: 0.045,
      pool: { desktop: 6, mobile: 3 },
      flicker: {
        idleRate: 4.7,
        idleDepth: 0.022,
        faultFloor: 0.025,
        recovery: 0.18,
      },
    },
  },
  audio: {
    drips: false,
    masterGain: 0.7,
    humGain: 0.068,
    oscillators: [
      { frequency: 60, type: 'sine', gain: 0.22 },
      { frequency: 120, type: 'triangle', gain: 0.065 },
      { frequency: 180, type: 'sine', gain: 0.025 },
      { frequency: 31, type: 'sine', gain: 0.09 },
    ],
    noise: { filter: 'bandpass', frequency: 610, q: 0.52, gain: 0.03 },
    heartbeat: { startFrequency: 64, endFrequency: 36 },
    impact: { startFrequency: 51, endFrequency: 19 },
    footstep: { walkLowpass: 240, runLowpass: 310 },
    ambience: {
      interval: [11, 24],
      cues: ['ballast-pop', 'distant-knock', 'fluorescent-dropout'],
      stereoWidth: 0.72,
      silenceChance: 0.34,
    },
  },
  objective: {
    type: 'none',
    count: 0,
    color: 0x86a77d,
    labels: {
      hud: 'FIND A WAY OUT',
      item: '',
      itemPlural: '',
      interact: 'E  OPEN',
      progress: '',
      locked: '',
      complete: 'EXIT LOCATED',
    },
  },
  props: [
    { type: 'square-column', density: 0.038, color: 0xaaa05e, accent: 0x70683d, cluster: [1, 3] },
    { type: 'ceiling-vent', density: 0.026, color: 0x686858, accent: 0x272820, cluster: [1, 2] },
    { type: 'discarded-chair', density: 0.014, color: 0x4f4b34, accent: 0x25251e, cluster: [1, 1] },
    { type: 'discarded-chair', density: 0.006, color: 0x66593d, accent: 0x2b2921, cluster: [2, 4] },
  ],
  incidents: {
    density: 0.012,
    minCount: 2,
    maxCount: 6,
    minCellDistance: 3,
    weights: {
      'collapsed-wanderer': 0.4,
      'abandoned-pack': 1.25,
      'chair-pile': 1.8,
      'black-motes': 0.55,
      'shoe-trail': 1.3,
    },
  },
  atmosphere: {
    identity: 'overlit-uncanny-office',
    cadence: { first: [10, 17], interval: [16, 29] },
    pauseDuringChase: true,
    environmentalStory: [
      { id: 'capacity', text: 'MEETING ROOM 4 / CAPACITY 0', density: 0.008, placement: 'wall' },
      { id: 'evacuation', text: 'EVACUATION ROUTE: RETURN TO DESK', density: 0.006, placement: 'wall' },
      { id: 'ceiling-log', text: 'TILE 07 REPLACED / TILE 07 REPLACED', density: 0.004, placement: 'fixture' },
    ],
    milestones: [],
    events: [
      {
        id: 'ballast-behind',
        earliest: 12,
        weight: 1.25,
        maxRepeats: 2,
        tension: [0.08, 0.78],
        message: 'THE LIGHT BEHIND YOU STOPPED HUMMING',
        duration: 1.15,
        cue: 'ballast-pop',
        effect: { flicker: 1.25, silence: 0.8 },
      },
      {
        id: 'warm-carpet',
        earliest: 20,
        weight: 0.7,
        maxRepeats: 1,
        tension: [0.12, 0.7],
        message: 'THE CARPET IS WARM HERE',
        duration: 1.05,
        cue: 'sub-bass-bump',
      },
      {
        id: 'wrong-corridor',
        earliest: 28,
        weight: 0.9,
        maxRepeats: 2,
        tension: [0.18, 0.82],
        message: 'THIS CORRIDOR WAS SHORTER BEFORE',
        duration: 1.2,
        cue: 'distant-knock',
        effect: { glitch: 0.42 },
      },
      {
        id: 'telephone',
        earliest: 34,
        weight: 0.56,
        maxRepeats: 1,
        tension: [0.2, 0.72],
        message: 'A TELEPHONE RINGS BEYOND THE WALL',
        duration: 1.15,
        cue: 'distant-ring',
        pan: 'random',
      },
      {
        id: 'ventilation-stop',
        earliest: 42,
        weight: 0.74,
        maxRepeats: 1,
        tension: [0.26, 0.88],
        message: 'THE VENTILATION IS HOLDING ITS BREATH',
        duration: 1.25,
        cue: 'fluorescent-dropout',
        effect: { flicker: 0.7, silence: 1.7 },
      },
    ],
  },
  equipment: {
    flashlight: {
      color: 0xffe7a0,
      intensity: 48,
      distance: 17,
      angle: 0.44,
      drainPerSecond: 0.0052,
      emergencyRechargePerSecond: 0.0022,
      flashCost: 0.28,
    },
  },
  evidence: {
    recharge: 0.34,
    entries: [
      'ARCHIVE 01 / THIS OFFICE HAS NO STREET ADDRESS',
      'ARCHIVE 02 / THE HUM CHANGES WHEN YOU BLINK',
      'ARCHIVE 03 / EVERY EXIT GOES ONE FLOOR LOWER',
    ],
  },
  monster: {
    name: 'The Still',
    identity: 'still',
    presentation: {
      silhouette: 'wire-rib-sentinel',
      eyePulse: 0,
      twitchStrength: 1.25,
    },
    sound: {
      breathPitch: 0.54,
      breathWeight: 0.44,
      stepWeight: 0.62,
      drag: 0.24,
    },
    skin: {
      type: 'faceless-shadow',
      body: 0x050604,
      accent: 0x11130f,
      eye: null,
      emissiveIntensity: 0,
      scale: 1.08,
    },
    timing: {
      firstScare: [9, 15],
      scareInterval: [13, 27],
      firstChase: [37, 51],
      glimpseDuration: 1.25,
      stalkDuration: 21,
      pathRefresh: { stalk: 0.8, chase: 0.36 },
    },
    behavior: {
      sight: { range: 25, peripheralDot: 0.32, acquireRate: 1.08, threshold: 0.5 },
      hearing: { baseCells: 2, noiseCells: 7, chaseNoise: 0.82, reacquireNoise: 0.5 },
      chase: { lostSightDelay: 4.8, searchDuration: [7, 11], recovery: [18, 26] },
      wanderCells: [3, 7],
    },
    speeds: { watched: 0.2, stalk: 1.16, chase: 3.34 },
    stalkTriggerDistance: 10.8,
    catchDistance: 0.88,
  },
};
