// Auto-discovered campaign chapter; keep this module data-only and deterministic.
export default {
  id: 'office-atrium',
  index: 10,
  name: 'Office Atrium',
  exit: { label: 'LIFT 00' },
  copy: {
    classification: 'THRESHOLD ARCHIVE / LEVEL 10',
    status: 'CORPORATE CAMPUS UNOCCUPIED',
    start: {
      kicker: 'CENTRAL ATRIUM / BUSINESS HOURS',
      title: 'THE SKY ABOVE<br />IS A CEILING.',
      body: 'Restore three lift relays. Reception has been expecting you since before hiring.',
      button: 'ENTER LEVEL 10',
    },
    pause: {
      kicker: 'MEETING PLACED ON HOLD',
      title: 'PLEASE STAY<br />ON THE LINE.',
      body: 'Every office phone shows the same incoming extension: yours.',
      button: 'REJOIN MEETING',
    },
    death: {
      kicker: 'EMPLOYEE RECORD ARCHIVED',
      title: 'POSITION<br />FILLED.',
      body: 'Your badge photo has appeared on every empty desk.',
      button: 'CLOCK IN AGAIN',
    },
    win: {
      kicker: 'LIFT 00 RESPONDS',
      title: 'NO BUTTON<br />POINTS UP.',
      body: 'The doors open onto tile, rails, and moving air from a train that never arrives.',
      button: 'DESCEND TO LEVEL 11',
    },
  },
  maze: {
    desktop: { cols: 31, rows: 23 },
    mobile: { cols: 23, rows: 17 },
    loopRatio: 0.36,
    roomDivisor: 40,
    minimumRooms: 13,
    roomSize: { min: 3, max: 6 },
    seedSalt: 0xa7710f1e,
  },
  surfaces: {
    wall: {
      base: [168, 177, 181],
      accent: [93, 111, 121],
      grime: [47, 54, 58],
      pattern: 'aged-wallpaper',
      roughness: 0.72,
      metalness: 0.04,
      bumpScale: 0.035,
      grimeOpacity: 0.14,
    },
    floor: {
      base: [104, 112, 117],
      accent: [62, 73, 80],
      grime: [32, 38, 42],
      pattern: 'oil-stained-concrete',
      roughness: 0.44,
      metalness: 0.08,
      bumpScale: 0.02,
    },
    ceiling: {
      base: [187, 194, 196],
      accent: [133, 144, 149],
      grime: [70, 80, 84],
      pattern: 'acoustic-tile',
      roughness: 0.89,
      metalness: 0.01,
      bumpScale: 0.03,
      emissive: 0x33434b,
      emissiveIntensity: 0.32,
    },
    trim: { color: 0x536a75, roughness: 0.54, metalness: 0.3 },
  },
  fog: { color: 0x6f7f86, density: { desktop: 0.022, mobile: 0.028 } },
  lighting: {
    exposure: 1,
    hemisphere: {
      sky: 0xd9f0fa,
      ground: 0x1d262b,
      intensity: { desktop: 0.72, mobile: 0.8 },
    },
    ambient: { color: 0x9dbac7, intensity: { desktop: 0.31, mobile: 0.38 } },
    fixture: {
      color: 0xdaf4ff,
      panelColor: 0xe8f8ff,
      deadPanelColor: 0x46555c,
      intensity: 116,
      distance: 14,
      angle: 1.28,
      penumbra: 0.94,
      decay: 2,
      brokenChance: 0.12,
      pool: { desktop: 9, mobile: 5 },
      flicker: { idleRate: 5.6, idleDepth: 0.018, faultFloor: 0.03, recovery: 0.27 },
    },
  },
  audio: {
    drips: false,
    masterGain: 0.66,
    humGain: 0.038,
    oscillators: [
      { frequency: 60, type: 'sine', gain: 0.15 },
      { frequency: 120, type: 'sine', gain: 0.026 },
      { frequency: 240, type: 'triangle', gain: 0.012 },
    ],
    noise: { filter: 'highpass', frequency: 910, q: 0.55, gain: 0.018 },
    heartbeat: { startFrequency: 70, endFrequency: 37 },
    impact: { startFrequency: 55, endFrequency: 21 },
    footstep: { walkLowpass: 360, runLowpass: 455 },
    ambience: {
      interval: [12, 27],
      cues: ['distant-ring', 'relay-chatter', 'machine-dropout', 'fluorescent-dropout'],
      stereoWidth: 0.88,
      silenceChance: 0.28,
    },
  },
  objective: {
    type: 'fuse',
    count: 3,
    color: 0x8ccae1,
    labels: {
      hud: 'RESTORE LIFT 00 RELAYS',
      item: 'LIFT RELAY',
      itemPlural: 'LIFT RELAYS',
      interact: 'E  RESET RELAY',
      progress: 'RELAYS {current}/{total}',
      locked: 'LIFT 00 AWAITS POWER',
      complete: 'LIFT 00 CALLED / RETURN TO ATRIUM',
    },
  },
  props: [
    { type: 'square-column', density: 0.021, color: 0xa7b0b4, accent: 0x526a76, cluster: [1, 4] },
    { type: 'discarded-chair', density: 0.024, color: 0x485a62, accent: 0x809aa6, cluster: [2, 5] },
    { type: 'ceiling-vent', density: 0.065, color: 0x829096, accent: 0x3c484d, cluster: [1, 4] },
    { type: 'cable-tray', density: 0.042, color: 0x59656a, accent: 0x252c2f, cluster: [2, 5] },
    { type: 'service-crate', density: 0.012, color: 0x50585a, accent: 0x8ca1aa, cluster: [1, 2] },
  ],
  incidents: {
    density: 0.013,
    minCount: 3,
    maxCount: 8,
    minCellDistance: 5,
    weights: {
      'collapsed-wanderer': 0.65,
      'abandoned-pack': 1.55,
      'chair-pile': 1.35,
      'black-motes': 0.75,
      'shoe-trail': 1.05,
    },
    palette: { cloth: 0x40545e, clothLight: 0x8298a2, motes: 0x10181b },
  },
  atmosphere: {
    identity: 'corporate-atrium-without-sky',
    cadence: { first: [10, 17], interval: [16, 29] },
    pauseDuringChase: true,
    environmentalStory: [
      { id: 'tenant-board', text: 'TENANTS: VACANT / EMPLOYEES PRESENT: 1', density: 0.009, placement: 'wall' },
      { id: 'floor-logo', text: 'WELCOME BACK / FIRST DAY: TOMORROW', density: 0.007, placement: 'floor' },
      { id: 'relay-label', text: 'LIFT 00 / CAPACITY: ONE MEMORY', density: 0.006, placement: 'objective' },
    ],
    milestones: [
      {
        id: 'atrium-first-relay',
        progress: 0.33,
        message: 'EVERY OFFICE PHONE LIGHTS UP WITHOUT RINGING',
        duration: 1.2,
        cue: 'relay-chatter',
        effect: { flicker: 0.28 },
      },
      {
        id: 'atrium-lift-called',
        progress: 1,
        message: 'LIFT 00 ARRIVES FROM A FLOOR BELOW ZERO',
        duration: 1.3,
        cue: 'machine-dropout',
        effect: { silence: 1.1, glitch: 0.24 },
      },
    ],
    events: [
      {
        id: 'conference-call', earliest: 8, weight: 1.15, maxRepeats: 3,
        tension: [0.03, 0.84], message: 'A CONFERENCE PHONE ANSWERS ITSELF', duration: 1.1,
        cue: 'distant-ring', pan: 'random',
      },
      {
        id: 'printer-page', earliest: 18, weight: 0.86, maxRepeats: 2,
        tension: [0.1, 0.86], message: 'A PRINTER PRODUCES A PAGE WITH YOUR CURRENT VIEW', duration: 1.22,
        cue: 'relay-chatter', effect: { glitch: 0.22 },
      },
      {
        id: 'lift-crossing', earliest: 29, weight: 0.62, maxRepeats: 2,
        tension: [0.18, 0.93], message: 'A LIFT CROSSES BEHIND THE WALL HORIZONTALLY', duration: 1.25,
        cue: 'machine-dropout', pan: 'random',
      },
      {
        id: 'lights-resign', earliest: 43, weight: 0.4, maxRepeats: 1,
        tension: [0.29, 0.91], message: 'THE LIGHTS SWITCH OFF IN THE SHAPE OF A PERSON', duration: 1.3,
        cue: 'fluorescent-dropout', effect: { flicker: 1.05, silence: 1.35 },
      },
    ],
  },
  equipment: {
    flashlight: {
      color: 0xd9f4ff,
      intensity: 52,
      distance: 20.5,
      angle: 0.43,
      drainPerSecond: 0.0049,
      emergencyRechargePerSecond: 0.0022,
      flashCost: 0.27,
    },
  },
  evidence: {
    recharge: 0.32,
    entries: [
      'HR FILE 001 / EMPLOYEE START DATE REPEATS EVERY MONDAY',
      'MEETING NOTES / ATTENDEE SPOKE FROM INSIDE THE LIFT SHAFT',
      'BADGE AUDIT / YOUR CARD OPENED THE BUILDING BEFORE YOU ARRIVED',
    ],
  },
  monster: {
    name: 'The Receptionist',
    identity: 'still',
    presentation: { silhouette: 'wire-rib-sentinel', eyePulse: 0.05, twitchStrength: 0.68 },
    sound: { breathPitch: 0.76, breathWeight: 0.36, stepWeight: 0.55, drag: 0.14 },
    skin: {
      type: 'faceless-shadow',
      body: 0x05090b,
      accent: 0x253a43,
      eye: null,
      emissiveIntensity: 0,
      scale: 1.06,
    },
    timing: {
      firstScare: [13, 21],
      scareInterval: [16, 29],
      firstChase: [50, 69],
      glimpseDuration: 1.42,
      stalkDuration: 25,
      pathRefresh: { stalk: 0.76, chase: 0.34 },
    },
    behavior: {
      sight: { range: 29, peripheralDot: 0.2, acquireRate: 0.98, threshold: 0.57 },
      hearing: { baseCells: 2.2, noiseCells: 8.5, chaseNoise: 0.8, reacquireNoise: 0.46 },
      chase: { lostSightDelay: 5.6, searchDuration: [8, 15], recovery: [19, 29] },
      wanderCells: [5, 10],
    },
    speeds: { watched: 0.12, stalk: 1.22, chase: 3.55 },
    stalkTriggerDistance: 13.2,
    catchDistance: 0.9,
  },
};
