export const LEVELS = [
  {
    id: 'level-0',
    index: 0,
    name: 'The Lobby',
    copy: {
      classification: 'THRESHOLD ARCHIVE / LEVEL 0',
      status: 'SIGNAL LOST',
      start: {
        kicker: 'UNVERIFIED FOOTAGE',
        title: 'YOU WERE<br />NEVER HERE.',
        body: 'The carpet is damp. The lights know where you are.',
        button: 'ENTER LEVEL 0',
      },
      pause: {
        kicker: 'CONNECTION INTERRUPTED',
        title: 'DON\'T STAND<br />STILL.',
        body: 'Something keeps moving when the picture stops.',
        button: 'KEEP MOVING',
      },
      death: {
        kicker: 'SUBJECT NOT RECOVERED',
        title: 'IT FOUND<br />YOU.',
        body: 'The footage continues for another eleven minutes.',
        button: 'WAKE UP AGAIN',
      },
      win: {
        kicker: 'THRESHOLD CROSSED',
        title: 'THE STAIRS<br />GO DOWN.',
        body: 'The exit did not lead outside. Warm machinery breathes below.',
        button: 'DESCEND TO LEVEL 1',
      },
    },
    maze: {
      desktop: { cols: 25, rows: 25 },
      mobile: { cols: 19, rows: 19 },
      loopRatio: 0.19,
      roomDivisor: 54,
      minimumRooms: 10,
      roomSize: { min: 2, max: 4 },
      seedSalt: 0x9e3779b9,
    },
    surfaces: {
      wall: {
        base: [183, 174, 91],
        accent: [156, 145, 68],
        grime: [59, 54, 25],
        pattern: 'aged-wallpaper',
        roughness: 0.93,
        metalness: 0,
        bumpScale: 0.045,
      },
      floor: {
        base: [92, 83, 48],
        accent: [67, 59, 34],
        grime: [46, 44, 24],
        pattern: 'damp-carpet',
        roughness: 1,
        metalness: 0,
        bumpScale: 0.072,
      },
      ceiling: {
        base: [178, 176, 148],
        accent: [146, 143, 118],
        grime: [92, 89, 67],
        pattern: 'acoustic-tile',
        roughness: 0.92,
        metalness: 0,
        bumpScale: 0.035,
        emissive: 0x312f1d,
        emissiveIntensity: 0.32,
      },
      trim: { color: 0x746b42, roughness: 0.92, metalness: 0 },
    },
    fog: {
      color: 0x676448,
      density: { desktop: 0.029, mobile: 0.036 },
    },
    lighting: {
      exposure: 0.82,
      hemisphere: {
        sky: 0xd8cb83,
        ground: 0x282613,
        intensity: { desktop: 0.62, mobile: 0.68 },
      },
      ambient: {
        color: 0x8e8550,
        intensity: { desktop: 0.22, mobile: 0.28 },
      },
      fixture: {
        color: 0xffefad,
        panelColor: 0xfff0b0,
        deadPanelColor: 0x4a4935,
        intensity: 94,
        distance: 11.5,
        angle: 1.26,
        penumbra: 0.92,
        decay: 2,
        brokenChance: 0.075,
        pool: { desktop: 6, mobile: 3 },
      },
    },
    audio: {
      masterGain: 0.72,
      humGain: 0.055,
      oscillators: [
        { frequency: 60, type: 'sine', gain: 0.22 },
        { frequency: 120, type: 'triangle', gain: 0.065 },
        { frequency: 180, type: 'sine', gain: 0.025 },
        { frequency: 31, type: 'sine', gain: 0.09 },
      ],
      noise: { filter: 'bandpass', frequency: 580, q: 0.46, gain: 0.025 },
      heartbeat: { startFrequency: 64, endFrequency: 36 },
      impact: { startFrequency: 51, endFrequency: 19 },
      footstep: { walkLowpass: 240, runLowpass: 310 },
    },
    objective: {
      type: 'none',
      count: 0,
      color: 0x86a77d,
      labels: {
        hud: 'FIND A WAY OUT',
        item: '',
        itemPlural: '',
        interact: 'E  OPEN',
        progress: '',
        locked: '',
        complete: 'EXIT LOCATED',
      },
    },
    props: [
      { type: 'square-column', density: 0.045, color: 0xaaa05e, accent: 0x70683d },
      { type: 'ceiling-vent', density: 0.018, color: 0x686858, accent: 0x272820 },
      { type: 'discarded-chair', density: 0.01, color: 0x4f4b34, accent: 0x25251e },
    ],
    monster: {
      name: 'The Still',
      skin: {
        type: 'faceless-shadow',
        body: 0x050604,
        accent: 0x11130f,
        eye: null,
        emissiveIntensity: 0,
        scale: 1.08,
      },
      timing: {
        firstScare: [14, 20],
        scareInterval: [15, 31],
        firstChase: [48, 63],
        glimpseDuration: 1.65,
        stalkDuration: 18,
        pathRefresh: { stalk: 0.9, chase: 0.42 },
      },
      speeds: { watched: 0.32, stalk: 1.08, chase: 3.15 },
      stalkTriggerDistance: 10,
      catchDistance: 0.92,
    },
  },
  {
    id: 'level-1',
    index: 1,
    name: 'Maintenance',
    copy: {
      classification: 'THRESHOLD ARCHIVE / LEVEL 1',
      status: 'AUXILIARY POWER OFFLINE',
      start: {
        kicker: 'SERVICE CORRIDOR 01',
        title: 'THE MACHINES<br />ARE BREATHING.',
        body: 'Three fuse boxes feed the freight lift. Restore them before the halls wake up.',
        button: 'ENTER LEVEL 1',
      },
      pause: {
        kicker: 'FEED DESYNCHRONIZED',
        title: 'IT HEARD<br />THE SILENCE.',
        body: 'The pipes are still knocking. Something else has stopped.',
        button: 'RESTORE FEED',
      },
      death: {
        kicker: 'MAINTENANCE LOG CLOSED',
        title: 'SHIFT<br />TERMINATED.',
        body: 'A fourth set of footsteps was recorded after contact ended.',
        button: 'CLOCK IN AGAIN',
      },
      win: {
        kicker: 'FREIGHT LIFT ACTIVE',
        title: 'THE ONLY WAY<br />IS LOWER.',
        body: 'The lift doors open onto wet concrete and a current of cold air.',
        button: 'DESCEND TO LEVEL 2',
      },
    },
    maze: {
      desktop: { cols: 27, rows: 23 },
      mobile: { cols: 21, rows: 17 },
      loopRatio: 0.13,
      roomDivisor: 72,
      minimumRooms: 7,
      roomSize: { min: 2, max: 3 },
      seedSalt: 0x85ebca6b,
    },
    surfaces: {
      wall: {
        base: [102, 105, 91],
        accent: [73, 77, 68],
        grime: [39, 42, 36],
        pattern: 'painted-concrete',
        roughness: 0.88,
        metalness: 0.04,
        bumpScale: 0.064,
      },
      floor: {
        base: [70, 71, 64],
        accent: [50, 51, 47],
        grime: [38, 35, 28],
        pattern: 'oil-stained-concrete',
        roughness: 0.9,
        metalness: 0.02,
        bumpScale: 0.052,
      },
      ceiling: {
        base: [76, 79, 72],
        accent: [53, 56, 51],
        grime: [35, 37, 33],
        pattern: 'service-slab',
        roughness: 0.87,
        metalness: 0.06,
        bumpScale: 0.048,
        emissive: 0x182016,
        emissiveIntensity: 0.18,
      },
      trim: { color: 0x42473f, roughness: 0.78, metalness: 0.18 },
    },
    fog: {
      color: 0x30352f,
      density: { desktop: 0.034, mobile: 0.041 },
    },
    lighting: {
      exposure: 0.7,
      hemisphere: {
        sky: 0xa7b291,
        ground: 0x171a16,
        intensity: { desktop: 0.42, mobile: 0.49 },
      },
      ambient: {
        color: 0x5d6654,
        intensity: { desktop: 0.16, mobile: 0.22 },
      },
      fixture: {
        color: 0xd8e8bd,
        panelColor: 0xddecc7,
        deadPanelColor: 0x343a32,
        intensity: 82,
        distance: 10.2,
        angle: 1.18,
        penumbra: 0.82,
        decay: 2,
        brokenChance: 0.19,
        pool: { desktop: 6, mobile: 3 },
      },
    },
    audio: {
      masterGain: 0.74,
      humGain: 0.061,
      oscillators: [
        { frequency: 50, type: 'sine', gain: 0.2 },
        { frequency: 100, type: 'sawtooth', gain: 0.035 },
        { frequency: 25, type: 'sine', gain: 0.13 },
        { frequency: 240, type: 'triangle', gain: 0.018 },
      ],
      noise: { filter: 'bandpass', frequency: 410, q: 0.72, gain: 0.032 },
      heartbeat: { startFrequency: 61, endFrequency: 34 },
      impact: { startFrequency: 46, endFrequency: 17 },
      footstep: { walkLowpass: 360, runLowpass: 470 },
    },
    objective: {
      type: 'fuse',
      count: 3,
      color: 0xe0a43e,
      labels: {
        hud: 'RESTORE POWER',
        item: 'FUSE',
        itemPlural: 'FUSES',
        interact: 'E  REPLACE FUSE',
        progress: 'FUSES {current}/{total}',
        locked: 'FREIGHT LIFT HAS NO POWER',
        complete: 'POWER RESTORED / FIND THE LIFT',
      },
    },
    props: [
      { type: 'wall-pipe', density: 0.12, color: 0x555c55, accent: 0x252a26 },
      { type: 'cable-tray', density: 0.045, color: 0x353a36, accent: 0x171a18 },
      { type: 'service-crate', density: 0.028, color: 0x695c3e, accent: 0x302b20 },
      { type: 'oil-drum', density: 0.018, color: 0x50594d, accent: 0xa36b28 },
    ],
    monster: {
      name: 'The Foreman',
      skin: {
        type: 'maintenance-husk',
        body: 0x151816,
        accent: 0x9c5b22,
        eye: 0xffd08a,
        emissiveIntensity: 1.8,
        scale: 1.12,
      },
      timing: {
        firstScare: [10, 16],
        scareInterval: [12, 24],
        firstChase: [38, 52],
        glimpseDuration: 1.35,
        stalkDuration: 16,
        pathRefresh: { stalk: 0.72, chase: 0.34 },
      },
      speeds: { watched: 0.48, stalk: 1.26, chase: 3.48 },
      stalkTriggerDistance: 11,
      catchDistance: 0.96,
    },
  },
  {
    id: 'level-2',
    index: 2,
    name: 'Lower Tunnels',
    copy: {
      classification: 'THRESHOLD ARCHIVE / LEVEL 2',
      status: 'FLOOD CONTROL FAILURE',
      start: {
        kicker: 'LOWER ACCESS / SUBLEVEL 2',
        title: 'THE WATER<br />IS RISING.',
        body: 'Open four drain valves. Do not follow the splashing when it moves against the current.',
        button: 'ENTER LEVEL 2',
      },
      pause: {
        kicker: 'CAMERA SUBMERGED',
        title: 'HOLD YOUR<br />BREATH.',
        body: 'Ripples continue across the feed while you are standing still.',
        button: 'SURFACE',
      },
      death: {
        kicker: 'DEPTH SENSOR OFFLINE',
        title: 'PULLED<br />UNDER.',
        body: 'The tunnel is only ankle-deep. Recovery divers found no bottom.',
        button: 'WADE BACK IN',
      },
      win: {
        kicker: 'DRAIN CYCLE COMPLETE',
        title: 'DAYLIGHT<br />IS A RECORDING.',
        body: 'A steel hatch opens above you. Birds can be heard on the other side.',
        button: 'RETURN TO LEVEL 0',
      },
    },
    maze: {
      desktop: { cols: 23, rows: 29 },
      mobile: { cols: 17, rows: 23 },
      loopRatio: 0.09,
      roomDivisor: 96,
      minimumRooms: 5,
      roomSize: { min: 2, max: 3 },
      seedSalt: 0xc2b2ae35,
    },
    surfaces: {
      wall: {
        base: [76, 91, 88],
        accent: [48, 66, 65],
        grime: [24, 39, 38],
        pattern: 'seeping-concrete',
        roughness: 0.96,
        metalness: 0.01,
        bumpScale: 0.082,
      },
      floor: {
        base: [47, 59, 58],
        accent: [32, 45, 45],
        grime: [18, 30, 29],
        pattern: 'flooded-concrete',
        roughness: 0.46,
        metalness: 0.03,
        bumpScale: 0.028,
      },
      ceiling: {
        base: [61, 73, 70],
        accent: [39, 52, 51],
        grime: [21, 34, 33],
        pattern: 'dripping-concrete',
        roughness: 0.97,
        metalness: 0.01,
        bumpScale: 0.076,
        emissive: 0x121d1c,
        emissiveIntensity: 0.12,
      },
      trim: { color: 0x344b49, roughness: 0.9, metalness: 0.08 },
    },
    fog: {
      color: 0x1e3333,
      density: { desktop: 0.044, mobile: 0.052 },
    },
    lighting: {
      exposure: 0.62,
      hemisphere: {
        sky: 0x789893,
        ground: 0x101b1b,
        intensity: { desktop: 0.34, mobile: 0.42 },
      },
      ambient: {
        color: 0x405d5b,
        intensity: { desktop: 0.13, mobile: 0.2 },
      },
      fixture: {
        color: 0x9ac9c2,
        panelColor: 0xaed8d0,
        deadPanelColor: 0x263a39,
        intensity: 68,
        distance: 9.4,
        angle: 1.12,
        penumbra: 0.88,
        decay: 2,
        brokenChance: 0.31,
        pool: { desktop: 5, mobile: 3 },
      },
    },
    audio: {
      masterGain: 0.76,
      humGain: 0.066,
      oscillators: [
        { frequency: 43, type: 'sine', gain: 0.24 },
        { frequency: 86, type: 'triangle', gain: 0.052 },
        { frequency: 21, type: 'sine', gain: 0.15 },
        { frequency: 172, type: 'sine', gain: 0.016 },
      ],
      noise: { filter: 'lowpass', frequency: 290, q: 0.58, gain: 0.04 },
      heartbeat: { startFrequency: 58, endFrequency: 31 },
      impact: { startFrequency: 39, endFrequency: 14 },
      footstep: { walkLowpass: 190, runLowpass: 250 },
    },
    objective: {
      type: 'valve',
      count: 4,
      color: 0x55b7b0,
      labels: {
        hud: 'DRAIN THE TUNNELS',
        item: 'VALVE',
        itemPlural: 'VALVES',
        interact: 'E  OPEN VALVE',
        progress: 'VALVES {current}/{total}',
        locked: 'PRESSURE LOCKED / OPEN ALL VALVES',
        complete: 'DRAIN CYCLE ACTIVE / FIND THE HATCH',
      },
    },
    props: [
      { type: 'wall-pipe', density: 0.16, color: 0x3c5755, accent: 0x1d302f },
      { type: 'standing-water', density: 0.14, color: 0x294d4d, accent: 0x6caaa4 },
      { type: 'drain-grate', density: 0.035, color: 0x293a39, accent: 0x101918 },
      { type: 'hanging-chain', density: 0.018, color: 0x3d4c49, accent: 0x172120 },
    ],
    monster: {
      name: 'The Wader',
      skin: {
        type: 'waterlogged-longlimb',
        body: 0x0c1918,
        accent: 0x34514d,
        eye: 0xa9d7ce,
        emissiveIntensity: 0.55,
        scale: 1.17,
      },
      timing: {
        firstScare: [8, 14],
        scareInterval: [10, 20],
        firstChase: [32, 45],
        glimpseDuration: 1.15,
        stalkDuration: 14,
        pathRefresh: { stalk: 0.58, chase: 0.28 },
      },
      speeds: { watched: 0.6, stalk: 1.42, chase: 3.72 },
      stalkTriggerDistance: 12,
      catchDistance: 1,
    },
  },
];

export function getLevelIndex(searchParams) {
  let rawLevel;

  if (searchParams && typeof searchParams.get === 'function') {
    rawLevel = searchParams.get('level');
  } else if (typeof searchParams === 'string') {
    rawLevel = new URLSearchParams(searchParams).get('level');
  } else if (searchParams && typeof searchParams === 'object') {
    rawLevel = searchParams.level;
  }

  const parsedLevel = Number(rawLevel);
  if (!Number.isFinite(parsedLevel)) return 0;
  return Math.max(0, Math.min(LEVELS.length - 1, Math.trunc(parsedLevel)));
}
