// Auto-discovered campaign chapter; keep this module data-only and deterministic.
export default {
  id: 'parking-structure',
  index: 8,
  name: 'Parking Structure',
  exit: { label: 'RAMP B' },
  copy: {
    classification: 'THRESHOLD ARCHIVE / LEVEL 8',
    status: 'VENTILATION FAILURE',
    start: {
      kicker: 'SUBLEVEL P4 / VEHICLE COUNT ZERO',
      title: 'ENGINES IDLE<br />WITHOUT CARS.',
      body: 'Reset four ventilation fuses. Every ramp returns one floor lower.',
      button: 'ENTER LEVEL 8',
    },
    pause: {
      kicker: 'PARKING FEED FROZEN',
      title: 'DO NOT FOLLOW<br />THE HEADLIGHTS.',
      body: 'Tire marks are forming on concrete behind you.',
      button: 'RETURN TO P4',
    },
    death: {
      kicker: 'SPACE OCCUPIED',
      title: 'PAYMENT<br />OVERDUE.',
      body: 'The ticket machine prints the exact time you stopped breathing.',
      button: 'RAISE GATE',
    },
    win: {
      kicker: 'RAMP B CLEARED',
      title: 'THE ARROW<br />POINTS BELOW.',
      body: 'Painted cinderblock gives way to rows of classroom doors.',
      button: 'DESCEND TO LEVEL 9',
    },
  },
  maze: {
    desktop: { cols: 29, rows: 21 },
    mobile: { cols: 21, rows: 17 },
    loopRatio: 0.4,
    roomDivisor: 62,
    minimumRooms: 7,
    roomSize: { min: 3, max: 6 },
    seedSalt: 0x8cab1e55,
  },
  surfaces: {
    wall: {
      base: [129, 125, 116],
      accent: [176, 118, 62],
      grime: [45, 42, 38],
      pattern: 'painted-concrete',
      roughness: 0.9,
      metalness: 0.02,
      bumpScale: 0.07,
      grimeOpacity: 0.24,
    },
    floor: {
      base: [75, 75, 72],
      accent: [116, 91, 58],
      grime: [27, 28, 28],
      pattern: 'oil-stained-concrete',
      roughness: 0.72,
      metalness: 0.04,
      bumpScale: 0.052,
    },
    ceiling: {
      base: [105, 103, 98],
      accent: [78, 77, 72],
      grime: [42, 41, 39],
      pattern: 'service-slab',
      roughness: 0.94,
      metalness: 0.01,
      bumpScale: 0.065,
      emissive: 0x342518,
      emissiveIntensity: 0.2,
    },
    trim: { color: 0x5f4d3b, roughness: 0.72, metalness: 0.2 },
  },
  fog: { color: 0x493c31, density: { desktop: 0.038, mobile: 0.044 } },
  lighting: {
    exposure: 0.8,
    hemisphere: {
      sky: 0xd5ab78,
      ground: 0x171512,
      intensity: { desktop: 0.48, mobile: 0.56 },
    },
    ambient: { color: 0x9d7652, intensity: { desktop: 0.2, mobile: 0.27 } },
    fixture: {
      color: 0xffb66f,
      panelColor: 0xffc184,
      deadPanelColor: 0x493d32,
      intensity: 94,
      distance: 14.5,
      angle: 1.3,
      penumbra: 0.82,
      decay: 2,
      brokenChance: 0.25,
      pool: { desktop: 8, mobile: 4 },
      flicker: { idleRate: 2.9, idleDepth: 0.048, faultFloor: 0.015, recovery: 0.42 },
    },
  },
  audio: {
    drips: true,
    masterGain: 0.78,
    humGain: 0.064,
    oscillators: [
      { frequency: 42, type: 'sine', gain: 0.26 },
      { frequency: 84, type: 'triangle', gain: 0.05 },
      { frequency: 21, type: 'sine', gain: 0.14 },
      { frequency: 168, type: 'sawtooth', gain: 0.008 },
    ],
    noise: { filter: 'lowpass', frequency: 310, q: 0.65, gain: 0.045 },
    heartbeat: { startFrequency: 62, endFrequency: 32 },
    impact: { startFrequency: 40, endFrequency: 14 },
    footstep: { walkLowpass: 205, runLowpass: 275 },
    ambience: {
      interval: [9, 21],
      cues: ['relay-chatter', 'machine-dropout', 'pressure-groan', 'distant-knock'],
      stereoWidth: 1,
      silenceChance: 0.15,
    },
  },
  objective: {
    type: 'fuse',
    count: 4,
    color: 0xe59a4f,
    labels: {
      hud: 'RESTORE EXHAUST VENTILATION',
      item: 'FAN BREAKER',
      itemPlural: 'FAN BREAKERS',
      interact: 'E  RESET BREAKER',
      progress: 'EXHAUST FANS {current}/{total}',
      locked: 'RAMP B GATE HAS NO POWER',
      complete: 'VENTILATION ONLINE / FIND RAMP B',
    },
  },
  props: [
    { type: 'parking-barrier', density: 0.026, color: 0x8e8a80, accent: 0xb9783e, cluster: [1, 4] },
    { type: 'oil-drum', density: 0.017, color: 0x514941, accent: 0xa06b3e, cluster: [1, 3] },
    { type: 'standing-water', density: 0.062, color: 0x3e4646, accent: 0x9b8265, cluster: [2, 6] },
    { type: 'cable-tray', density: 0.06, color: 0x55514b, accent: 0x242321, cluster: [2, 5] },
    { type: 'wall-pipe', density: 0.07, color: 0x675e53, accent: 0x2c2925, cluster: [2, 5] },
  ],
  incidents: {
    density: 0.018,
    minCount: 4,
    maxCount: 9,
    minCellDistance: 5,
    weights: {
      'collapsed-wanderer': 0.75,
      'abandoned-pack': 1.2,
      'chair-pile': 0.3,
      'black-motes': 1.45,
      'shoe-trail': 1.7,
    },
    palette: { cloth: 0x4b4540, clothLight: 0x8d7966, motes: 0x0a0908 },
  },
  atmosphere: {
    identity: 'endless-sublevel-parking',
    cadence: { first: [8, 15], interval: [14, 25] },
    pauseDuringChase: true,
    environmentalStory: [
      { id: 'parking-arrow', text: 'RAMP B ↓ / STREET LEVEL ↑ 47 FLOORS', density: 0.01, placement: 'wall' },
      { id: 'tire-print', text: 'TREAD ENDS HERE / ENGINE CONTINUES', density: 0.008, placement: 'floor' },
      { id: 'fan-warning', text: 'CO DETECTOR: BREATHING / VEHICLES: NONE', density: 0.006, placement: 'objective' },
    ],
    milestones: [
      {
        id: 'garage-two-fans',
        progress: 0.5,
        message: 'EXHAUST FANS TURN AGAINST THE AIRFLOW',
        duration: 1.22,
        cue: 'machine-dropout',
        effect: { flicker: 0.48 },
      },
      {
        id: 'garage-all-fans',
        progress: 1,
        message: 'HEADLIGHTS SWEEP ACROSS THE EMPTY LEVEL',
        duration: 1.28,
        cue: 'relay-chatter',
        effect: { glitch: 0.32 },
      },
    ],
    events: [
      {
        id: 'remote-alarm', earliest: 6, weight: 1.2, maxRepeats: 3,
        tension: [0.02, 0.86], message: 'A CAR ALARM CHIRPS ONE LEVEL BELOW', duration: 1.08,
        cue: 'relay-chatter', pan: 'random',
      },
      {
        id: 'rolling-tire', earliest: 15, weight: 0.9, maxRepeats: 2,
        tension: [0.09, 0.84], message: 'RUBBER ROLLS THROUGH THE DARK AND NEVER PASSES', duration: 1.18,
        cue: 'chain-drag', pan: 'random',
      },
      {
        id: 'engine-start', earliest: 26, weight: 0.65, maxRepeats: 2,
        tension: [0.17, 0.92], message: 'AN ENGINE STARTS INSIDE A CONCRETE WALL', duration: 1.24,
        cue: 'pressure-groan', effect: { flicker: 0.4 },
      },
      {
        id: 'garage-silence', earliest: 41, weight: 0.44, maxRepeats: 1,
        tension: [0.28, 0.91], message: 'THE FANS STOP. FOOTSTEPS CONTINUE.', duration: 1.3,
        cue: 'machine-dropout', effect: { silence: 1.6, flicker: 0.75 },
      },
    ],
  },
  equipment: {
    flashlight: {
      color: 0xffd0a0,
      intensity: 61,
      distance: 22,
      angle: 0.39,
      drainPerSecond: 0.0062,
      emergencyRechargePerSecond: 0.0018,
      flashCost: 0.32,
    },
  },
  evidence: {
    recharge: 0.27,
    entries: [
      'PARKING STUB 044 / ENTRY TIME PRECEDES CONSTRUCTION BY 31 YEARS',
      'MAINTENANCE LOG / FAN FOUR EXHAUSTS INTO FAN ONE',
      'PAYMENT RECEIPT / BALANCE DUE: ONE MEMORY OF DAYLIGHT',
    ],
  },
  monster: {
    name: 'The Valet',
    identity: 'foreman',
    presentation: { silhouette: 'asymmetric-maintenance-husk', eyePulse: 0.48, twitchStrength: 0.72 },
    sound: { breathPitch: 0.55, breathWeight: 0.75, stepWeight: 1.08, drag: 0.42 },
    skin: {
      type: 'maintenance-husk',
      body: 0x0b0a09,
      accent: 0x6f3d1f,
      eye: 0xffa04a,
      emissiveIntensity: 0.48,
      scale: 1.16,
    },
    timing: {
      firstScare: [11, 19],
      scareInterval: [13, 24],
      firstChase: [43, 60],
      glimpseDuration: 1.18,
      stalkDuration: 22,
      pathRefresh: { stalk: 0.55, chase: 0.25 },
    },
    behavior: {
      sight: { range: 27, peripheralDot: 0.16, acquireRate: 1.38, threshold: 0.45 },
      hearing: { baseCells: 4.2, noiseCells: 14, chaseNoise: 0.6, reacquireNoise: 0.34 },
      chase: { lostSightDelay: 6.2, searchDuration: [10, 17], recovery: [14, 21] },
      wanderCells: [5, 11],
    },
    speeds: { watched: 0.48, stalk: 1.42, chase: 3.82 },
    stalkTriggerDistance: 13.4,
    catchDistance: 0.96,
  },
};
